if ((!(place_meeting(x, y, obj_enemy_spared))) && enemyhealth > 0 && enemyhurt == 0 && enemydead == 0)
    draw_sprite(healthysprite, 0, x, y)
if place_meeting(x, y, obj_enemy_spared)
    draw_sprite(spr_jane_battle_down, 1, x, y)
if (enemyhurt == 1 && enemydead == 0 && (!(place_meeting(x, y, obj_enemy_spareable))) && enemyhealth > 0)
    draw_sprite(spr_jane_battle_down, 0, x, y)
if (enemyhurt == 1 && enemydead == 0 && (!(place_meeting(x, y, obj_enemy_spareable))) && enemyhealth <= 0)
    draw_sprite(spr_jane_battle_down, 0, x, y)
if (enemyhurt == 1 && enemydead == 0 && place_meeting(x, y, obj_enemy_spareable))
    draw_sprite(spr_jane_battle_down, 0, x, y)
if (enemydead == 1)
    draw_sprite_ext(spr_jane_battle_headless, 0, x, y, 1, 1, 0, image_blend, image_alpha)
if ((!(place_meeting(x, y, obj_enemy_spared))) && enemyhealth <= 0 && enemyhurt == 0 && enemydead == 0)
    draw_sprite(spr_jane_battle_headless, 0, x, y)
if (enemyhealth <= 0 && instance_exists(obj_evade_ground))
    draw_sprite_ext(spr_soul, 0, global.soulxposition, global.soulyposition, 0.5, 0.5, 0, image_blend, image_alpha)
scr_enemy_draw_healthbar()

