function scr_draw_hats() {
	if ((!instance_exists(obj_mbm_darkness)) && (!instance_exists(obj_soul_tobattle)) && (!instance_exists(obj_fake_soul_tobattle)))
	{
	    if (global.playername == "Jacket")
	    {
	        if (sprite_index == spr_pro_stand)
	            draw_sprite(spr_ph1_stand, image_index, x, y)
	        if (sprite_index == spr_pro_down)
	            draw_sprite(spr_ph1_down, image_index, x, y)
	        if (sprite_index == spr_pro_right)
	            draw_sprite(spr_ph1_right, image_index, x, y)
	        if (sprite_index == spr_pro_up)
	            draw_sprite(spr_ph1_up, image_index, x, y)
	        if (sprite_index == spr_pro_left)
	            draw_sprite(spr_ph1_left, image_index, x, y)
	        if (sprite_index == spr_pbeer_beer || sprite_index == spr_pbeer_stand || sprite_index == spr_pbeer_pour)
	            draw_sprite(spr_ph1_stand, 3, x, y)
	        if (sprite_index == spr_pbeer_left)
	            draw_sprite(spr_ph1_left, image_index, x, y)
	        if (sprite_index == spr_soul_flashing)
	        {
	            if instance_exists(obj_protagonist)
	                draw_sprite(spr_ph1_stand, obj_protagonist.prodirection, obj_protagonist.x, obj_protagonist.y)
	            if instance_exists(obj_pro_stopped)
	                draw_sprite(spr_ph1_stand, obj_pro_stopped.image_index, obj_pro_stopped.x, obj_pro_stopped.y)
	        }
	    }
	    else if (global.playername == "Robot" || global.playername == "Robutt" || global.playername == "Robots")
	    {
	        if (sprite_index == spr_pro_stand)
	            draw_sprite(spr_ph2_stand, image_index, x, y)
	        if (sprite_index == spr_pro_down)
	            draw_sprite(spr_ph2_down, image_index, x, y)
	        if (sprite_index == spr_pro_right)
	            draw_sprite(spr_ph2_right, image_index, x, y)
	        if (sprite_index == spr_pro_left)
	            draw_sprite(spr_ph2_left, image_index, x, y)
	        if (sprite_index == spr_pbeer_beer || sprite_index == spr_pbeer_stand || sprite_index == spr_pbeer_pour)
	            draw_sprite(spr_ph2_stand, 3, x, y)
	        if (sprite_index == spr_pbeer_left)
	            draw_sprite(spr_ph2_left, image_index, x, y)
	        if (sprite_index == spr_soul_flashing)
	        {
	            if instance_exists(obj_protagonist)
	                draw_sprite(spr_ph2_stand, obj_protagonist.prodirection, obj_protagonist.x, obj_protagonist.y)
	            if instance_exists(obj_pro_stopped)
	                draw_sprite(spr_ph2_stand, obj_pro_stopped.image_index, obj_pro_stopped.x, obj_pro_stopped.y)
	        }
	    }
	    else if (global.playername == "Nino" || global.playername == "Jill" || global.playername == "Dashie")
	    {
	        if (sprite_index == spr_pro_stand)
	            draw_sprite(spr_ph3_stand, image_index, x, y)
	        if (sprite_index == spr_pro_down)
	            draw_sprite(spr_ph3_down, image_index, x, y)
	        if (sprite_index == spr_pro_right)
	            draw_sprite(spr_ph3_right, image_index, x, y)
	        if (sprite_index == spr_pro_up)
	            draw_sprite(spr_ph3_up, image_index, x, y)
	        if (sprite_index == spr_pro_left)
	            draw_sprite(spr_ph3_left, image_index, x, y)
	        if (sprite_index == spr_pbeer_beer || sprite_index == spr_pbeer_stand || sprite_index == spr_pbeer_pour)
	            draw_sprite(spr_ph3_stand, 3, x, y)
	        if (sprite_index == spr_pbeer_left)
	            draw_sprite(spr_ph3_left, image_index, x, y)
	        if (sprite_index == spr_soul_flashing)
	        {
	            if instance_exists(obj_protagonist)
	                draw_sprite(spr_ph3_stand, obj_protagonist.prodirection, obj_protagonist.x, obj_protagonist.y)
	            if instance_exists(obj_pro_stopped)
	                draw_sprite(spr_ph3_stand, obj_pro_stopped.image_index, obj_pro_stopped.x, obj_pro_stopped.y)
	        }
	    }
	    else if (global.playername == "Temmie")
	    {
	        if (sprite_index == spr_pro_stand)
	            draw_sprite(spr_ph4_stand, image_index, x, y)
	        if (sprite_index == spr_pro_down)
	            draw_sprite(spr_ph4_down, image_index, x, y)
	        if (sprite_index == spr_pro_right)
	            draw_sprite(spr_ph4_right, image_index, x, y)
	        if (sprite_index == spr_pro_up)
	            draw_sprite(spr_ph4_up, image_index, x, y)
	        if (sprite_index == spr_pro_left)
	            draw_sprite(spr_ph4_left, image_index, x, y)
	        if (sprite_index == spr_pbeer_beer || sprite_index == spr_pbeer_stand || sprite_index == spr_pbeer_pour)
	            draw_sprite(spr_ph4_stand, 3, x, y)
	        if (sprite_index == spr_pbeer_left)
	            draw_sprite(spr_ph4_left, image_index, x, y)
	        if (sprite_index == spr_soul_flashing)
	        {
	            if instance_exists(obj_protagonist)
	                draw_sprite(spr_ph4_stand, obj_protagonist.prodirection, obj_protagonist.x, obj_protagonist.y)
	            if instance_exists(obj_pro_stopped)
	                draw_sprite(spr_ph4_stand, obj_pro_stopped.image_index, obj_pro_stopped.x, obj_pro_stopped.y)
	        }
	    }
	    else if (global.playername == "Toby")
	    {
	        if (sprite_index == spr_pro_stand)
	            draw_sprite(spr_ph5_stand, image_index, x, y)
	        if (sprite_index == spr_pro_down)
	            draw_sprite(spr_ph5_down, image_index, x, y)
	        if (sprite_index == spr_pro_right)
	            draw_sprite(spr_ph5_right, image_index, x, y)
	        if (sprite_index == spr_pro_up)
	            draw_sprite(spr_ph5_up, image_index, x, y)
	        if (sprite_index == spr_pro_left)
	            draw_sprite(spr_ph5_left, image_index, x, y)
	        if (sprite_index == spr_pbeer_beer || sprite_index == spr_pbeer_stand || sprite_index == spr_pbeer_pour)
	            draw_sprite(spr_ph5_stand, 3, x, y)
	        if (sprite_index == spr_pbeer_left)
	            draw_sprite(spr_ph5_left, image_index, x, y)
	        if (sprite_index == spr_soul_flashing)
	        {
	            if instance_exists(obj_protagonist)
	                draw_sprite(spr_ph5_stand, obj_protagonist.prodirection, obj_protagonist.x, obj_protagonist.y)
	            if instance_exists(obj_pro_stopped)
	                draw_sprite(spr_ph5_stand, obj_pro_stopped.image_index, obj_pro_stopped.x, obj_pro_stopped.y)
	        }
	    }
	    else if (global.playername == "Maxbox" || global.playername == "MaxBox")
	    {
	        if (sprite_index == spr_pro_stand)
	            draw_sprite(spr_ph6_stand, image_index, x, y)
	        if (sprite_index == spr_pro_down)
	            draw_sprite(spr_ph6_down, image_index, x, y)
	        if (sprite_index == spr_pro_right)
	            draw_sprite(spr_ph6_right, image_index, x, y)
	        if (sprite_index == spr_pro_left)
	            draw_sprite(spr_ph6_left, image_index, x, y)
	        if (sprite_index == spr_pbeer_beer || sprite_index == spr_pbeer_stand || sprite_index == spr_pbeer_pour)
	            draw_sprite(spr_ph6_stand, 3, x, y)
	        if (sprite_index == spr_pbeer_left)
	            draw_sprite(spr_ph6_left, image_index, x, y)
	        if (sprite_index == spr_soul_flashing)
	        {
	            if instance_exists(obj_protagonist)
	                draw_sprite(spr_ph6_stand, obj_protagonist.prodirection, obj_protagonist.x, obj_protagonist.y)
	            if instance_exists(obj_pro_stopped)
	                draw_sprite(spr_ph6_stand, obj_pro_stopped.image_index, obj_pro_stopped.x, obj_pro_stopped.y)
	        }
	    }
	    else if (global.playername == "Isaac")
	    {
	        if (sprite_index == spr_pro_stand)
	            draw_sprite(spr_ph7_stand, image_index, x, y)
	        if (sprite_index == spr_pro_down)
	            draw_sprite(spr_ph7_down, image_index, x, y)
	        if (sprite_index == spr_pro_right)
	            draw_sprite(spr_ph7_right, image_index, x, y)
	        if (sprite_index == spr_pro_left)
	            draw_sprite(spr_ph7_left, image_index, x, y)
	        if (sprite_index == spr_pbeer_beer || sprite_index == spr_pbeer_stand || sprite_index == spr_pbeer_pour)
	            draw_sprite(spr_ph7_stand, 3, x, y)
	        if (sprite_index == spr_pbeer_left)
	            draw_sprite(spr_ph7_left, image_index, x, y)
	        if (sprite_index == spr_soul_flashing)
	        {
	            if instance_exists(obj_protagonist)
	                draw_sprite(spr_ph7_stand, obj_protagonist.prodirection, obj_protagonist.x, obj_protagonist.y)
	            if instance_exists(obj_pro_stopped)
	                draw_sprite(spr_ph7_stand, obj_pro_stopped.image_index, obj_pro_stopped.x, obj_pro_stopped.y)
	        }
	    }
	    else if (global.playername == "Batter")
	    {
	        if (sprite_index == spr_pro_stand)
	            draw_sprite(spr_ph8_stand, image_index, x, y)
	        if (sprite_index == spr_pro_down)
	            draw_sprite(spr_ph8_down, image_index, x, y)
	        if (sprite_index == spr_pro_right)
	            draw_sprite(spr_ph8_right, image_index, x, y)
	        if (sprite_index == spr_pro_up)
	            draw_sprite(spr_ph8_up, image_index, x, y)
	        if (sprite_index == spr_pro_left)
	            draw_sprite(spr_ph8_left, image_index, x, y)
	        if (sprite_index == spr_pbeer_beer || sprite_index == spr_pbeer_stand || sprite_index == spr_pbeer_pour)
	            draw_sprite(spr_ph8_stand, 3, x, y)
	        if (sprite_index == spr_pbeer_left)
	            draw_sprite(spr_ph8_left, image_index, x, y)
	        if (sprite_index == spr_soul_flashing)
	        {
	            if instance_exists(obj_protagonist)
	                draw_sprite(spr_ph8_stand, obj_protagonist.prodirection, obj_protagonist.x, obj_protagonist.y)
	            if instance_exists(obj_pro_stopped)
	                draw_sprite(spr_ph8_stand, obj_pro_stopped.image_index, obj_pro_stopped.x, obj_pro_stopped.y)
	        }
	    }
	    else if (global.playername == "Ness")
	    {
	        if (sprite_index == spr_pro_stand)
	            draw_sprite(spr_ph9_stand, image_index, x, y)
	        if (sprite_index == spr_pro_down)
	            draw_sprite(spr_ph9_down, image_index, x, y)
	        if (sprite_index == spr_pro_right)
	            draw_sprite(spr_ph9_right, image_index, x, y)
	        if (sprite_index == spr_pro_up)
	            draw_sprite(spr_ph9_up, image_index, x, y)
	        if (sprite_index == spr_pro_left)
	            draw_sprite(spr_ph9_left, image_index, x, y)
	        if (sprite_index == spr_pbeer_beer || sprite_index == spr_pbeer_stand || sprite_index == spr_pbeer_pour)
	            draw_sprite(spr_ph9_stand, 3, x, y)
	        if (sprite_index == spr_pbeer_left)
	            draw_sprite(spr_ph9_left, image_index, x, y)
	        if (sprite_index == spr_soul_flashing)
	        {
	            if instance_exists(obj_protagonist)
	                draw_sprite(spr_ph9_stand, obj_protagonist.prodirection, obj_protagonist.x, obj_protagonist.y)
	            if instance_exists(obj_pro_stopped)
	                draw_sprite(spr_ph9_stand, obj_pro_stopped.image_index, obj_pro_stopped.x, obj_pro_stopped.y)
	        }
	    }
	    else if (global.playername == "FUNKe" || global.playername == "Funke" || global.playername == "Justyn")
	    {
	        if (sprite_index == spr_pro_stand)
	            draw_sprite(spr_ph10_stand, image_index, x, y)
	        if (sprite_index == spr_pro_down)
	            draw_sprite(spr_ph10_down, image_index, x, y)
	        if (sprite_index == spr_pro_right)
	            draw_sprite(spr_ph10_right, image_index, x, y)
	        if (sprite_index == spr_pro_up)
	            draw_sprite(spr_ph10_up, image_index, x, y)
	        if (sprite_index == spr_pro_left)
	            draw_sprite(spr_ph10_left, image_index, x, y)
	        if (sprite_index == spr_pbeer_beer || sprite_index == spr_pbeer_stand || sprite_index == spr_pbeer_pour)
	            draw_sprite(spr_ph10_stand, 3, x, y)
	        if (sprite_index == spr_pbeer_left)
	            draw_sprite(spr_ph10_left, image_index, x, y)
	        if (sprite_index == spr_soul_flashing)
	        {
	            if instance_exists(obj_protagonist)
	                draw_sprite(spr_ph10_stand, obj_protagonist.prodirection, obj_protagonist.x, obj_protagonist.y)
	            if instance_exists(obj_pro_stopped)
	                draw_sprite(spr_ph10_stand, obj_pro_stopped.image_index, obj_pro_stopped.x, obj_pro_stopped.y)
	        }
	    }
	    else if (global.playername == "Vinny")
	    {
	        if (sprite_index == spr_pro_stand)
	            draw_sprite(spr_ph11_stand, image_index, x, y)
	        if (sprite_index == spr_pro_down)
	            draw_sprite(spr_ph11_down, image_index, x, y)
	        if (sprite_index == spr_pro_right)
	            draw_sprite(spr_ph11_right, image_index, x, y)
	        if (sprite_index == spr_pro_up)
	            draw_sprite(spr_ph11_up, image_index, x, y)
	        if (sprite_index == spr_pro_left)
	            draw_sprite(spr_ph11_left, image_index, x, y)
	        if (sprite_index == spr_pbeer_beer || sprite_index == spr_pbeer_stand || sprite_index == spr_pbeer_pour)
	            draw_sprite(spr_ph11_stand, 3, x, y)
	        if (sprite_index == spr_pbeer_left)
	            draw_sprite(spr_ph11_left, image_index, x, y)
	        if (sprite_index == spr_soul_flashing)
	        {
	            if instance_exists(obj_protagonist)
	                draw_sprite(spr_ph11_stand, obj_protagonist.prodirection, obj_protagonist.x, obj_protagonist.y)
	            if instance_exists(obj_pro_stopped)
	                draw_sprite(spr_ph11_stand, obj_pro_stopped.image_index, obj_pro_stopped.x, obj_pro_stopped.y)
	        }
	    }
	    else if (global.playername == "Joel")
	    {
	        if (sprite_index == spr_pro_stand)
	            draw_sprite(spr_ph12_stand, image_index, x, y)
	        if (sprite_index == spr_pro_down)
	            draw_sprite(spr_ph12_down, image_index, x, y)
	        if (sprite_index == spr_pro_right)
	            draw_sprite(spr_ph12_right, image_index, x, y)
	        if (sprite_index == spr_pro_up)
	            draw_sprite(spr_ph12_up, image_index, x, y)
	        if (sprite_index == spr_pro_left)
	            draw_sprite(spr_ph12_left, image_index, x, y)
	        if (sprite_index == spr_pbeer_beer || sprite_index == spr_pbeer_stand || sprite_index == spr_pbeer_pour)
	            draw_sprite(spr_ph12_stand, 3, x, y)
	        if (sprite_index == spr_pbeer_left)
	            draw_sprite(spr_ph12_left, image_index, x, y)
	        if (sprite_index == spr_soul_flashing)
	        {
	            if instance_exists(obj_protagonist)
	                draw_sprite(spr_ph12_stand, obj_protagonist.prodirection, obj_protagonist.x, obj_protagonist.y)
	            if instance_exists(obj_pro_stopped)
	                draw_sprite(spr_ph12_stand, obj_pro_stopped.image_index, obj_pro_stopped.x, obj_pro_stopped.y)
	        }
	    }
	}



}
