draw_set_color(c_red)
draw_text(0, 0, string_hash_to_newline(("Genocide (F12) " + string(global.genocide))))
draw_text(0, 20, string_hash_to_newline(("Killed (F2/F3) " + string(global.enemieskilled))))
draw_text(0, 40, string_hash_to_newline(("Hired  (F4/F5) " + string(global.enemiesspared))))
draw_text(0, 60, string_hash_to_newline(("Sanikilled (F6) " + string(global.sanikilled))))
draw_text(0, 80, string_hash_to_newline(("Sniperkilled (F7) " + string(global.sniperkilled))))
draw_text(0, 100, string_hash_to_newline(("Janekilled (F8) " + string(global.janekilled))))
draw_text(0, 120, string_hash_to_newline(("Tavishkilled (F9) " + string(global.tavishkilled))))
draw_text(0, 140, string_hash_to_newline(("Spykilled (F10) " + string(global.spykilled))))
draw_text(0, 160, string_hash_to_newline(("Scoutkilled (F11) " + string(global.scoutkilled))))
draw_text(0, 180, string_hash_to_newline(("RLdellkilled (Enter) " + string(global.reloaddellkilled))))
draw_text(0, 200, string_hash_to_newline(("RLdellhired (Backspace) " + string(global.reloaddellhired))))
draw_text(0, 220, string_hash_to_newline(("Times died (Alt) " + string(global.delltimesdied))))
draw_set_color(c_white)

