STR[0] = "* Hello and welcome to#  the Mann Co. Store!"
STR[1] = "* Sell me stuff? Haha!#* I didn't get so rich#  buying everyone's garbage!#* I got so rich by#  selling it instead!"
STR[2] = "* You don't have enough Australium!#* Are you trying to scam me?#* Because that's what I am#  trying to do here!"
STR[3] = "* I am Saxton Hale,#  CEO of the Mann Co. Store!"
STR[4] = "* We sell products#  and get in fights!#* If you aren't 100 percent#  satisfied, you can take it#  up with me!"
STR[5] = "* Now stop talking, this isn't#  making me any money!"
STR[6] = ""
STR[7] = ""
STR[8] = "* Hey mate, your backpack's full.#* Clear it out and#  come back later."
STR[9] = "* Goodbye!#* Don't forget to come back#  later with more money!"
N = 0
POS = 0
CSTR = STR[N]
MAXSTR = 9
global.textboxon = 1
fontcolor = 16777215
fontname = 2
textvoice = 79
voicenow = 0
choices = 0
selected = 0
itemselected = 0
saxtonface = 0
leaving = 0
progress = 0
item1 = 0
price1 = 0
text1 = 0
item2 = 0
price2 = 0
text2 = 0
item3 = 0
price3 = 0
text3 = 0
item4 = 0
price4 = 0
text4 = 0
buytext = 0
buytalk1 = "What would#you like#to buy?"
buytalk2 = "Want to#buy this?"
buytalk3 = "If you#don't like#it, get#lost!"
roomname = 0
xpos = 0
ypos = 0
pdirection = 0
dontplay = 0

