draw_set_color(c_white)
draw_set_font(font_huge)
draw_text(214, 160, string_hash_to_newline("SPY"))
draw_set_color(c_yellow)
draw_set_font(font_standard)
draw_text(198, 198, string_hash_to_newline("Nowhere to#be seen"))
draw_sprite_ext(spr_blackscreen, 0, 180, 190, 1, 1, 0, image_blend, spyblack)
draw_set_color(c_white)
draw_set_font(font_huge)
draw_text(31, 160, string_hash_to_newline("SCOUT"))
draw_set_color(c_yellow)
draw_set_font(font_standard)
draw_text(25, 198, string_hash_to_newline("20,000 words#a minute"))
draw_sprite_ext(spr_blackscreen, 0, -200, 190, 1, 1, 0, image_blend, scoutblack)
draw_set_font(font_standard)
draw_set_color(c_white)

