scr_enemy_variables()
enemyname = "Spy"
enemyquip = "You never saw him before."
enemyinfo = "Here to interrogate you."
enemyhealth = 45
maxhealth = 45
sparemeter = 50
enemyattack = 4
enemydefense = 2
giantdamagebar = 1
cashreceive = 70
xpreceive = round(random_range(5, 9))
act1 = "Struggle"
act2 = "Struggle"
act3 = "Struggle"
act4 = "???"
healthysprite = 484
hurtsprite = 485
downsprite = 485
image_speed = 0
geno = 0
isdying = 0
dyingprogress = 0
shaking = 0
upordown = 0
leftorright = 0
armsangle = 0
head = 0
cloaked = 0
invisible = 0
jarated = 0
noshoot = 1
issparing = 0

