if (progress == 0)
    draw_sprite(spr_underteam, 0, __view_get( e__VW.XView, (0 << 0) ), __view_get( e__VW.YView, (0 << 0) ))
if (progress == 1)
    draw_sprite(spr_credits, 0, 0, 0)
if (progress == 2)
    draw_sprite(spr_credits, 1, 0, 0)
if (progress == 3)
    draw_sprite(spr_credits, 2, 0, 0)
if (progress == 4)
    draw_sprite(spr_credits, 3, 0, 0)
if (progress == 5)
    draw_sprite(spr_credits, 4, 0, 0)
if (progress == 6)
    draw_sprite(spr_credits, 5, 0, 0)
if (progress == 7)
    draw_sprite(spr_credits, 6, 0, 0)
if (progress == 8)
    draw_sprite(spr_credits, 7, 0, 0)
if (progress == 9)
    draw_sprite(spr_credits, 8, 0, 0)
draw_set_font(font_standard)
draw_set_color(c_white)

