draw_set_color(c_white)
draw_set_font(font_huge)
draw_text(160, 170, string_hash_to_newline("SANI"))
draw_text(250, 170, string_hash_to_newline("PYRO"))
draw_set_color(c_yellow)
draw_set_font(font_standard)
draw_text(130, 198, string_hash_to_newline("Reducing child#mortality rate"))
draw_text(262, 203, string_hash_to_newline("?????"))
draw_sprite_ext(spr_blackscreen, 0, 150, 200, 1, 1, 0, image_blend, saniblack)
draw_set_color(c_white)
draw_set_font(font_huge)
draw_text(9, 152, string_hash_to_newline("MISHA"))
draw_set_color(c_yellow)
draw_set_font(font_standard)
draw_text(12, 190, string_hash_to_newline("Mowing down#baby men"))
draw_sprite_ext(spr_blackscreen, 0, 30, 170, 1, 1, 0, image_blend, mishablack)
draw_set_font(font_standard)
draw_set_color(c_white)

