draw_set_font(font_standard)
draw_set_color(c_lime)
if (progress == 1)
    draw_text_ext(10, 10, string_hash_to_newline((("> " + string_copy(STR[0], 1, POS)) + string(underscore))), 18, 320)
if (progress > 1)
    draw_text_ext(10, 10, string_hash_to_newline((("> Insert your codename (" + string(remaining)) + " remaining).#> Press " + "\"" + "Space" + "\"" + " to continue.")), 18, 320)
if (progress == 4)
    draw_text_ext(10, 46, string_hash_to_newline((("> " + string(global.playername)) + string(underscore))), 18, 320)
if (progress > 4 && progress < 8)
    draw_text_ext(10, 46, string_hash_to_newline(("> " + string(global.playername))), 18, 320)
if (progress == 5)
    draw_text_ext(10, 64, string_hash_to_newline((("> " + string_copy(STR[1], 1, POS)) + string(underscore))), 18, 320)
if (progress > 5)
    draw_text_ext(10, 64, string_hash_to_newline(("> " + string(STR[1]))), 18, 320)
if (progress >= 9)
    draw_text_ext(10, 46, string_hash_to_newline("> "), 18, 320)
draw_sprite_ext(spr_blacklines, 0, 0, 0, 1, 1, 0, c_black, 0.3)
draw_sprite_ext(spr_blackscreen, 0, 0, 0, 1, 1, 0, image_blend, blackness)
if (progress >= 9)
{
    draw_set_color(make_color_rgb(104, 51, 85))
    draw_text_transformed((10 - (stretch * 10)), 46, string_hash_to_newline(("  " + string(global.playername))), (1 + stretch), (1 + stretch), 0)
    draw_set_color(c_lime)
}
draw_sprite_ext(spr_whitescreen, 0, 0, 0, 1, 1, 0, image_blend, whiteness)
draw_set_font(font_standard)
draw_set_color(c_white)
if (progress == 6)
{
    if (yesorno == 0)
        draw_sprite(spr_soul_small, 0, 39, 90)
    if (yesorno == 1)
        draw_sprite(spr_soul_small, 0, 135, 90)
}

