redtext = 1
stringamount = 7
string1 = "* ENTRY NUMBER NINE"
string2 = "* Weapons seem to be useless#  against these things."
string3 = "* But what if someone didn't#  even use weapons?"
string4 = "* Could an entirely#  defenseless person stop#  them somehow?"
string5 = "* I think I will release them#  onto Teufort."
string6 = "* A town of weaklings and#  cowards.#* They couldn't harm a fly."
string7 = "* They were able to survive#  through the most pacifistic#  ways possible."
string8 = "* I wonder if they can stop#  my soldiers..."
