STR[0] = "This is message Nr. 1."
STR[1] = "This is message Nr. 2."
STR[2] = "This is message Nr. 3."
STR[3] = "This is message Nr. 4."
STR[4] = "This is message Nr. 5."
STR[5] = "This is message Nr. 6."
STR[6] = "This is message Nr. 7."
STR[7] = "This is message Nr. 8."
STR[8] = "This is message Nr. 9."
STR[9] = "This is message Nr. 10."
N = 0
POS = 0
CSTR = STR[N]
MAXSTR = 9
fontcolor = 16777215
fontname = 1
textvoice = 80
textface = 0
facespeed = 0.5
facetalking = 0
voicenow = 0
dontplay = 0
atend = 0

