scr_enemy_variables()
enemyname = "Sani"
enemyquip = "He saved your life."
enemyinfo = "Seems reluctant to fight."
enemyhealth = 38
maxhealth = 38
sparemeter = 95
enemyattack = 4
enemydefense = 2
giantdamagebar = 1
xpreceive = 150
cashreceive = 0
act1 = "Talk"
act2 = "Talk"
act3 = "Talk"
act4 = "???"
healthysprite = 426
hurtsprite = 427
downsprite = 427
wavethere = 0
attackchance = choose(1, 2, 3, 4)
image_speed = 0
geno = 0
isdying = 0
genocideon = 0
global.hospitalprogress = 38
global.playerxpos = 1020
global.playerypos = 190

