function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // obj_global_variables
	global.__objectDepths[1] = 0; // obj_gamevariables
	global.__objectDepths[2] = -10000; // obj_controller
	global.__objectDepths[3] = 0; // obj_genocide_variables
	global.__objectDepths[4] = -50; // obj_activation_object
	global.__objectDepths[5] = 0; // obj_no_battle_zone
	global.__objectDepths[6] = 0; // obj_wait_for_me
	global.__objectDepths[7] = 0; // obj_music_player
	global.__objectDepths[8] = 0; // obj_skip_room
	global.__objectDepths[9] = -2000; // obj_room_fade_out
	global.__objectDepths[10] = -2000; // obj_room_fade_in
	global.__objectDepths[11] = 2000000; // obj_parallax_bg
	global.__objectDepths[12] = 0; // obj_nobody_room
	global.__objectDepths[13] = 0; // obj_game_saver
	global.__objectDepths[14] = -100; // obj_store
	global.__objectDepths[15] = -100; // obj_menu
	global.__objectDepths[16] = 0; // obj_starttimer
	global.__objectDepths[17] = 0; // obj_chat_activate
	global.__objectDepths[18] = 0; // obj_chattest
	global.__objectDepths[19] = -100000; // obj_playtest_helper
	global.__objectDepths[20] = -5; // oldbattlenpc
	global.__objectDepths[21] = 0; // obj_old_player_scripts
	global.__objectDepths[22] = -100; // obj_textbox_hunijkah
	global.__objectDepths[23] = 0; // old_roomchange
	global.__objectDepths[24] = -100; // old_textbox
	global.__objectDepths[25] = -5; // oldobj_sven_battle
	global.__objectDepths[26] = -3; // oldghostattack
	global.__objectDepths[27] = -5; // OLDobj_sani_dummy
	global.__objectDepths[28] = -10; // oldsyringegun
	global.__objectDepths[29] = 10000; // object246
	global.__objectDepths[30] = 10000; // OLDswordtest
	global.__objectDepths[31] = 0; // oldconveyorbelt
	global.__objectDepths[32] = -3; // OLDobj_merc_bullet
	global.__objectDepths[33] = 0; // undynetest
	global.__objectDepths[34] = 0; // olddispenserflying
	global.__objectDepths[35] = 0; // crabtest
	global.__objectDepths[36] = 0; // wizardtest
	global.__objectDepths[37] = 0; // singtest
	global.__objectDepths[38] = 0; // scouttest
	global.__objectDepths[39] = 0; // gordontest
	global.__objectDepths[40] = 0; // dispensertest
	global.__objectDepths[41] = 0; // OLDobj_intro4
	global.__objectDepths[42] = 0; // OLDobj_intro3
	global.__objectDepths[43] = 0; // OLDobj_intro2
	global.__objectDepths[44] = 0; // OLDgamevariables
	global.__objectDepths[45] = 0; // OLDmishabody
	global.__objectDepths[46] = 0; // obj_general_variables
	global.__objectDepths[47] = -20; // OLDPyrotest
	global.__objectDepths[48] = -120; // OLDobj_pl_soulmove2
	global.__objectDepths[49] = -4; // OLDobj_pl_gear
	global.__objectDepths[50] = -100; // OLDobj_pl_invisact1
	global.__objectDepths[51] = 0; // OLDobj_pl_nail
	global.__objectDepths[52] = 0; // OLDobj_pl_b_rocket
	global.__objectDepths[53] = 0; // OLDnailcreator
	global.__objectDepths[54] = 0; // oldpyrodrawgunandhp
	global.__objectDepths[55] = -5; // delltest
	global.__objectDepths[56] = -20; // object553
	global.__objectDepths[57] = -1000; // object577
	global.__objectDepths[58] = 0; // killincreaser
	global.__objectDepths[59] = 0; // countertest
	global.__objectDepths[60] = -5000; // EVADETIMESKIP
	global.__objectDepths[61] = 0; // Kittentest
	global.__objectDepths[62] = 0; // object754
	global.__objectDepths[63] = 0; // object721
	global.__objectDepths[64] = -3000; // calltester
	global.__objectDepths[65] = 0; // obj_camera
	global.__objectDepths[66] = -100; // obj_solid
	global.__objectDepths[67] = 0; // obj_talk_object
	global.__objectDepths[68] = 0; // obj_roomchange
	global.__objectDepths[69] = -30; // obj_protagonist
	global.__objectDepths[70] = 0; // obj_npc1
	global.__objectDepths[71] = 0; // obj_view_parent
	global.__objectDepths[72] = 0; // obj_save
	global.__objectDepths[73] = 0; // obj_apple
	global.__objectDepths[74] = 0; // obj_player_spawn
	global.__objectDepths[75] = 0; // obj_switch_template
	global.__objectDepths[76] = -100; // obj_text_box
	global.__objectDepths[77] = -10; // obj_text_box_battle
	global.__objectDepths[78] = -10; // obj_nobody_textbox
	global.__objectDepths[79] = -10; // obj_text_box_battle_end
	global.__objectDepths[80] = -10; // obj_speech_bubble
	global.__objectDepths[81] = -10; // obj_speech_bubble_noevade
	global.__objectDepths[82] = -100; // obj_textbox_death
	global.__objectDepths[83] = -110; // obj_textbox_item
	global.__objectDepths[84] = -100; // obj_save_box
	global.__objectDepths[85] = -10; // obj_text_box_misha
	global.__objectDepths[86] = -110; // obj_textface
	global.__objectDepths[87] = -35; // obj_com_exclamation
	global.__objectDepths[88] = -40; // obj_soul_battlestart
	global.__objectDepths[89] = -35; // obj_blackscreen
	global.__objectDepths[90] = -40; // obj_soul_tobattle
	global.__objectDepths[91] = -2000; // obj_soul_fadebattle
	global.__objectDepths[92] = 200; // obj_battle_bg
	global.__objectDepths[93] = -12; // obj_battle_gui
	global.__objectDepths[94] = -12; // obj_soul_battle_select
	global.__objectDepths[95] = -30; // obj_battle_ground
	global.__objectDepths[96] = 3; // obj_battle_enemy_select
	global.__objectDepths[97] = -35; // obj_target_choice
	global.__objectDepths[98] = 3; // obj_damaging_enemy
	global.__objectDepths[99] = 0; // obj_check_up
	global.__objectDepths[100] = 0; // obj_enemy_down
	global.__objectDepths[101] = 0; // obj_enemy_spared
	global.__objectDepths[102] = 0; // obj_enemy_spareable
	global.__objectDepths[103] = 5; // obj_enemy2_checkup
	global.__objectDepths[104] = 5; // obj_enemy1_checkup
	global.__objectDepths[105] = 5; // obj_enemy3_checkup
	global.__objectDepths[106] = 0; // obj_box_to_evade
	global.__objectDepths[107] = 0; // obj_evade_ground
	global.__objectDepths[108] = 0; // obj_evade_to_box
	global.__objectDepths[109] = -10; // obj_evade_soul
	global.__objectDepths[110] = -10; // obj_soul_ball
	global.__objectDepths[111] = -10; // obj_evade_shield
	global.__objectDepths[112] = 0; // obj_act_enemy_select
	global.__objectDepths[113] = 0; // obj_youact
	global.__objectDepths[114] = -50; // obj_soul_flee
	global.__objectDepths[115] = 0; // obj_fleedecide
	global.__objectDepths[116] = -30; // obj_battle_death
	global.__objectDepths[117] = 0; // obj_soul_bits
	global.__objectDepths[118] = 0; // obj_bit1
	global.__objectDepths[119] = 0; // obj_bit2
	global.__objectDepths[120] = 0; // obj_bit3
	global.__objectDepths[121] = 0; // obj_bit4
	global.__objectDepths[122] = 0; // obj_gameover_message
	global.__objectDepths[123] = 0; // obj_death_effect
	global.__objectDepths[124] = 0; // obj_spare_effect
	global.__objectDepths[125] = -9; // obj_sparedust
	global.__objectDepths[126] = -9; // obj_deathflames
	global.__objectDepths[127] = -35; // obj_miss
	global.__objectDepths[128] = -35; // obj_crit
	global.__objectDepths[129] = -35; // obj_betrayal_kill
	global.__objectDepths[130] = -34; // obj_damage_numbers
	global.__objectDepths[131] = 0; // obj_jarate_effect
	global.__objectDepths[132] = 0; // obj_jarate_drop
	global.__objectDepths[133] = -2000; // obj_battle_fade_out
	global.__objectDepths[134] = 0; // obj_fightwave
	global.__objectDepths[135] = 0; // obj_actwave
	global.__objectDepths[136] = 0; // obj_itemwave
	global.__objectDepths[137] = 0; // obj_sparewave
	global.__objectDepths[138] = 0; // obj_fleewave
	global.__objectDepths[139] = 0; // obj_battlenpc_parent
	global.__objectDepths[140] = 0; // obj_enemy_attack_parent
	global.__objectDepths[141] = -5; // obj_battlenpc_1
	global.__objectDepths[142] = -15; // obj_bullet_test
	global.__objectDepths[143] = -5; // obj_sven_battle
	global.__objectDepths[144] = -15; // obj_sven_saw_hor
	global.__objectDepths[145] = -15; // obj_sven_saw_hor2
	global.__objectDepths[146] = -15; // obj_sven_saw_vert
	global.__objectDepths[147] = -5; // obj_ccat_battle
	global.__objectDepths[148] = -15; // obj_ccat_tear
	global.__objectDepths[149] = -5; // obj_sani_dummy
	global.__objectDepths[150] = -5; // obj_zeph_battle
	global.__objectDepths[151] = -15; // obj_ghost_attack
	global.__objectDepths[152] = -5; // obj_sani_battle
	global.__objectDepths[153] = -15; // obj_sani_bonesaw
	global.__objectDepths[154] = -15; // obj_sani_needle
	global.__objectDepths[155] = -17; // obj_sani_syringe_gun
	global.__objectDepths[156] = -5; // obj_sniper_battle
	global.__objectDepths[157] = -15; // obj_tm_battle_bullet
	global.__objectDepths[158] = -15; // obj_tm_jar_shard
	global.__objectDepths[159] = -15; // obj_tm_jar
	global.__objectDepths[160] = -15; // obj_tm_jar_drop
	global.__objectDepths[161] = -15; // obj_tm_crosshair
	global.__objectDepths[162] = -15; // obj_tm_battle_bullet2
	global.__objectDepths[163] = -5; // obj_magpie_battle
	global.__objectDepths[164] = -15; // obj_magpie_feather
	global.__objectDepths[165] = -5; // obj_greater_birb
	global.__objectDepths[166] = -15; // obj_small_birb
	global.__objectDepths[167] = -5; // obj_jane_battle
	global.__objectDepths[168] = -15; // obj_jane_rocket
	global.__objectDepths[169] = -8; // obj_jane_head
	global.__objectDepths[170] = -5; // obj_bites_battle
	global.__objectDepths[171] = 10000; // obj_jane_extra_box
	global.__objectDepths[172] = 5; // obj_tavish_battle
	global.__objectDepths[173] = -15; // obj_m_demointro
	global.__objectDepths[174] = -15; // obj_tavish_swordpiece
	global.__objectDepths[175] = -15; // obj_m_risesword
	global.__objectDepths[176] = -2500; // obj_m_whitescreen
	global.__objectDepths[177] = -5; // obj_cackle_battle
	global.__objectDepths[178] = -15; // obj_cackle_fire
	global.__objectDepths[179] = -5; // obj_miniculus_battle
	global.__objectDepths[180] = -15; // obj_miniculus_eye
	global.__objectDepths[181] = -5; // obj_merc1_battle
	global.__objectDepths[182] = -5; // obj_merc2_battle
	global.__objectDepths[183] = -5; // obj_merc3_battle
	global.__objectDepths[184] = 0; // obj_spy_battle
	global.__objectDepths[185] = 0; // obj_smoke_spawn
	global.__objectDepths[186] = -15; // obj_spy_crab
	global.__objectDepths[187] = -20; // obj_spy_smoke
	global.__objectDepths[188] = -5; // obj_slacker_battle
	global.__objectDepths[189] = -15; // obj_slacker_knife
	global.__objectDepths[190] = -5; // obj_stan_battle
	global.__objectDepths[191] = -15; // obj_stan_question
	global.__objectDepths[192] = -5; // obj_wizard_battle
	global.__objectDepths[193] = -15; // obj_wizard_thunder
	global.__objectDepths[194] = -17; // obj_wizard_hand
	global.__objectDepths[195] = -5; // obj_physician_battle
	global.__objectDepths[196] = -15; // obj_physician_crowbar
	global.__objectDepths[197] = 5; // obj_dispenser_battle
	global.__objectDepths[198] = -17; // obj_tiny_dispenser
	global.__objectDepths[199] = -17; // obj_tiny_dispenser2
	global.__objectDepths[200] = -15; // obj_tiny_disp_bolt
	global.__objectDepths[201] = -15; // obj_tiny_block
	global.__objectDepths[202] = -15; // obj_mc_tinyball
	global.__objectDepths[203] = -15; // obj_mc_tinydisp
	global.__objectDepths[204] = 5; // obj_scout_battle
	global.__objectDepths[205] = -15; // obj_scout_legattack
	global.__objectDepths[206] = 5; // obj_misha_battle
	global.__objectDepths[207] = 0; // obj_bullet_follow
	global.__objectDepths[208] = 0; // obj_bullet_follow2
	global.__objectDepths[209] = -15; // obj_misha_punchmode
	global.__objectDepths[210] = -30; // obj_heavy_eye
	global.__objectDepths[211] = -10; // obj_misha_punch
	global.__objectDepths[212] = -20; // obj_misha_punch2
	global.__objectDepths[213] = -20; // obj_misha_bullet
	global.__objectDepths[214] = -10; // obj_danger_zones
	global.__objectDepths[215] = -5; // obj_misha_death
	global.__objectDepths[216] = 0; // obj_misha_heart
	global.__objectDepths[217] = 0; // obj_misha_heartbit
	global.__objectDepths[218] = 0; // obj_misha_lastbox
	global.__objectDepths[219] = 2; // obj_misha_fightchoice
	global.__objectDepths[220] = 2; // obj_misha_mercychoice
	global.__objectDepths[221] = -10; // obj_misha_bottle
	global.__objectDepths[222] = -10; // obj_misha_bottle_shards
	global.__objectDepths[223] = -5; // obj_mbm_dell_intro
	global.__objectDepths[224] = -5; // obj_dell_battle
	global.__objectDepths[225] = -4; // obj_dell_box
	global.__objectDepths[226] = -20; // obj_frontier_justice
	global.__objectDepths[227] = -15; // obj_justice_blast
	global.__objectDepths[228] = -6; // obj_dell_platform
	global.__objectDepths[229] = 5; // obj_dell_wrench
	global.__objectDepths[230] = 5; // obj_dell_sidewrench
	global.__objectDepths[231] = -31; // obj_battle_bleeding
	global.__objectDepths[232] = 0; // obj_dell_sparefadeout
	global.__objectDepths[233] = -40; // obj_dell_extrasoul
	global.__objectDepths[234] = -50; // obj_dell_wrenchloop
	global.__objectDepths[235] = -150; // obj_dell_wrenchfight
	global.__objectDepths[236] = -15; // obj_dell_handattack
	global.__objectDepths[237] = -666; // obj_mbm_tele
	global.__objectDepths[238] = -7; // obj_dell_battle_sentry
	global.__objectDepths[239] = -15; // obj_dell_bullet
	global.__objectDepths[240] = 0; // obj_dell_evade_wall
	global.__objectDepths[241] = -5; // obj_dell_phasethree
	global.__objectDepths[242] = -6; // obj_dell_evade_floor
	global.__objectDepths[243] = 0; // obj_dell_extraground
	global.__objectDepths[244] = -2500; // obj_dell_whitescreen
	global.__objectDepths[245] = -10; // obj_dell_item
	global.__objectDepths[246] = 0; // obj_dell_death
	global.__objectDepths[247] = -6; // obj_dell_z
	global.__objectDepths[248] = 6; // obj_eli_battle
	global.__objectDepths[249] = -12; // obj_eli_battle_heals
	global.__objectDepths[250] = -5; // obj_lethal_battle
	global.__objectDepths[251] = -15; // obj_lethal_jaws
	global.__objectDepths[252] = -5; // obj_hurts_battle
	global.__objectDepths[253] = -14; // obj_ithurts_blade
	global.__objectDepths[254] = -15; // obj_ithurts_bladepiece
	global.__objectDepths[255] = -5; // obj_hunter_battle
	global.__objectDepths[256] = -10; // obj_hunter_arm
	global.__objectDepths[257] = -40; // obj_fake_soul_battlestart
	global.__objectDepths[258] = -40; // obj_fake_soul_tobattle
	global.__objectDepths[259] = -35; // obj_fake_blackscreen
	global.__objectDepths[260] = 0; // obj_fake_evade_ground
	global.__objectDepths[261] = -5; // obj_fake_evade_soul
	global.__objectDepths[262] = -2000; // obj_fake_soul_fadebattle
	global.__objectDepths[263] = -2000; // obj_fake_battle_fade_out
	global.__objectDepths[264] = -30; // obj_pro_stopped
	global.__objectDepths[265] = 0; // obj_path_left
	global.__objectDepths[266] = 0; // obj_h_ballooney1
	global.__objectDepths[267] = -10; // obj_ballooney_fake_battle
	global.__objectDepths[268] = -6; // obj_h_beer_bottle
	global.__objectDepths[269] = -6; // obj_h_beer_bottle_fly
	global.__objectDepths[270] = -6; // obj_h_beer_bottle_shard
	global.__objectDepths[271] = -2500; // obj_h_whitescreen
	global.__objectDepths[272] = -5; // obj_h_soul_arrows
	global.__objectDepths[273] = -10; // obj_sani1_moving
	global.__objectDepths[274] = 0; // obj_sani_encounter_stop
	global.__objectDepths[275] = -15; // obj_sani1_exc
	global.__objectDepths[276] = 0; // obj_h_switch1
	global.__objectDepths[277] = 0; // obj_h_spike1
	global.__objectDepths[278] = 0; // obj_h_spike1_down
	global.__objectDepths[279] = 0; // obj_sani2_wait
	global.__objectDepths[280] = 0; // obj_sani3_wait
	global.__objectDepths[281] = -10; // obj_h_dummy
	global.__objectDepths[282] = 0; // obj_sani4_stand
	global.__objectDepths[283] = 0; // obj_sani5_stand
	global.__objectDepths[284] = 0; // obj_sani6_stand
	global.__objectDepths[285] = 0; // obj_sani7_wait
	global.__objectDepths[286] = 0; // obj_h_runspikes_down
	global.__objectDepths[287] = 0; // obj_h_runspikes_up
	global.__objectDepths[288] = 0; // obj_h_habana
	global.__objectDepths[289] = 0; // obj_h_easter_egg
	global.__objectDepths[290] = 0; // obj_h_zepheniah_floor
	global.__objectDepths[291] = 0; // obj_h_zepheniah_after
	global.__objectDepths[292] = 0; // obj_h_number_button
	global.__objectDepths[293] = 5; // obj_h_number_spikes_up
	global.__objectDepths[294] = 10; // obj_h_number_spikes_down
	global.__objectDepths[295] = 0; // obj_h_number_check1
	global.__objectDepths[296] = 0; // obj_h_number_lever
	global.__objectDepths[297] = 0; // obj_h_number_lever_2
	global.__objectDepths[298] = 0; // obj_h_number_check2
	global.__objectDepths[299] = 0; // obj_sani8_stand
	global.__objectDepths[300] = -15; // obj_sani8_exc
	global.__objectDepths[301] = 0; // obj_sani8_stop
	global.__objectDepths[302] = 2; // obj_medigun_machine
	global.__objectDepths[303] = 0; // obj_noleave
	global.__objectDepths[304] = -35; // obj_sani9_rush
	global.__objectDepths[305] = 0; // obj_sani10_wait
	global.__objectDepths[306] = -35; // obj_sani11_to_surgery
	global.__objectDepths[307] = -10; // obj_sani12_surgery
	global.__objectDepths[308] = 15; // obj_h_target
	global.__objectDepths[309] = 5; // obj_h_medi_beam
	global.__objectDepths[310] = -10; // obj_sani13
	global.__objectDepths[311] = 0; // obj_sani14_leave
	global.__objectDepths[312] = 10; // obj_h_flee_spikes_down
	global.__objectDepths[313] = 0; // obj_h_flee_spikes_up
	global.__objectDepths[314] = 0; // obj_sani_h_goodbye
	global.__objectDepths[315] = 0; // obj_h_dove
	global.__objectDepths[316] = 0; // obj_h_ballooney2
	global.__objectDepths[317] = 0; // obj_h_leaving
	global.__objectDepths[318] = -2500; // obj_h_whitescreen2
	global.__objectDepths[319] = 0; // obj_h_bambam
	global.__objectDepths[320] = -35; // obj_tm_sentry1
	global.__objectDepths[321] = -15; // obj_sentry_exc
	global.__objectDepths[322] = 0; // obj_tm_dell1
	global.__objectDepths[323] = 0; // obj_tm_jane1
	global.__objectDepths[324] = -1; // obj_tm_jane2
	global.__objectDepths[325] = 0; // obj_tm_dell2
	global.__objectDepths[326] = 0; // obj_tm_dell3
	global.__objectDepths[327] = 0; // obj_tm_jane3
	global.__objectDepths[328] = -80; // obj_tm_grenade
	global.__objectDepths[329] = -100; // obj_tm_grenade_blink
	global.__objectDepths[330] = -20; // obj_tm_explosion
	global.__objectDepths[331] = 0; // obj_tm_wall_stop
	global.__objectDepths[332] = 0; // obj_tm_wall_noreturn1
	global.__objectDepths[333] = 0; // obj_tm_water_cooler
	global.__objectDepths[334] = 0; // obj_tm_habana
	global.__objectDepths[335] = 0; // obj_tm_bunnies
	global.__objectDepths[336] = 0; // obj_tm_fox
	global.__objectDepths[337] = 0; // obj_tm_dispenser
	global.__objectDepths[338] = 0; // obj_tm_mine
	global.__objectDepths[339] = 0; // obj_tm_mine_stop
	global.__objectDepths[340] = 0; // obj_tm_jane4
	global.__objectDepths[341] = 0; // obj_tm_wall_noreturn2
	global.__objectDepths[342] = 0; // obj_tm_jane5
	global.__objectDepths[343] = 5; // obj_tm_dell4
	global.__objectDepths[344] = 0; // obj_tm_dell5
	global.__objectDepths[345] = 0; // obj_tm_wall_noreturn3
	global.__objectDepths[346] = 0; // obj_tm_sniperstop
	global.__objectDepths[347] = 0; // obj_tm_sniperstop2
	global.__objectDepths[348] = 0; // obj_tm_spikebutton
	global.__objectDepths[349] = 0; // obj_tm_spikes1_down
	global.__objectDepths[350] = 0; // obj_tm_spikes1_up
	global.__objectDepths[351] = 0; // obj_tm_spikes2_up
	global.__objectDepths[352] = 0; // obj_tm_spikes3_up
	global.__objectDepths[353] = 0; // obj_tm_spikes3_down
	global.__objectDepths[354] = 0; // obj_tm_spikes2_down
	global.__objectDepths[355] = 0; // obj_tm_sniper_torso
	global.__objectDepths[356] = 0; // obj_tm_sniper_torso2
	global.__objectDepths[357] = 0; // obj_tm_sniper_torso3
	global.__objectDepths[358] = 0; // obj_tm_sniper_talk
	global.__objectDepths[359] = -31; // obj_tm_sniper_laser1
	global.__objectDepths[360] = -31; // obj_tm_sniper_laser2
	global.__objectDepths[361] = -2; // obj_tm_sniper_torso_rifle
	global.__objectDepths[362] = -2; // obj_tm_sniper_torso_rifle2
	global.__objectDepths[363] = 0; // obj_tm_sniper_bullet
	global.__objectDepths[364] = 0; // obj_tm_sniper_bullet2
	global.__objectDepths[365] = 0; // obj_tm_hereitcomes
	global.__objectDepths[366] = 0; // obj_tm_sniper_shooting
	global.__objectDepths[367] = 0; // obj_tm_dell6
	global.__objectDepths[368] = 0; // obj_tm_van_sniper
	global.__objectDepths[369] = -30; // obj_tm_sniper_van
	global.__objectDepths[370] = -32; // lasertest
	global.__objectDepths[371] = -31; // obj_sniperdot
	global.__objectDepths[372] = 0; // obj_db_van_sniper2
	global.__objectDepths[373] = 0; // obj_db_cakebomb
	global.__objectDepths[374] = 0; // obj_db_teufortians
	global.__objectDepths[375] = 0; // obj_db_dell
	global.__objectDepths[376] = 0; // obj_db_jane1
	global.__objectDepths[377] = 0; // obj_db_jane2
	global.__objectDepths[378] = 0; // obj_fake_jane_battle
	global.__objectDepths[379] = -7; // obj_battle_spraycan
	global.__objectDepths[380] = -6; // obj_battle_spray
	global.__objectDepths[381] = 0; // obj_db_trashcan
	global.__objectDepths[382] = 0; // obj_db_housebites
	global.__objectDepths[383] = 0; // obj_db_housejane
	global.__objectDepths[384] = 0; // obj_db_housearmor
	global.__objectDepths[385] = 0; // obj_db_housetavish
	global.__objectDepths[386] = 0; // obj_db_housedell
	global.__objectDepths[387] = 0; // obj_m_dell
	global.__objectDepths[388] = -31; // obj_m_tallgrass
	global.__objectDepths[389] = 0; // obj_m_waterfall
	global.__objectDepths[390] = 0; // obj_minecart
	global.__objectDepths[391] = 0; // obj_m_habana
	global.__objectDepths[392] = 0; // obj_m_miner
	global.__objectDepths[393] = 0; // obj_m_canary
	global.__objectDepths[394] = 0; // obj_m_canary2
	global.__objectDepths[395] = 0; // obj_m_mouse
	global.__objectDepths[396] = 0; // obj_m_dell2
	global.__objectDepths[397] = 0; // obj_m_dell3
	global.__objectDepths[398] = -1000; // obj_m_call1
	global.__objectDepths[399] = -1000; // obj_m_call2
	global.__objectDepths[400] = -1000; // obj_m_call3
	global.__objectDepths[401] = -200; // obj_m_tavishstop1
	global.__objectDepths[402] = 0; // obj_m_tavish1
	global.__objectDepths[403] = 0; // obj_m_jane
	global.__objectDepths[404] = 0; // obj_m_tavishcart
	global.__objectDepths[405] = 0; // obj_m_floorsword
	global.__objectDepths[406] = 0; // obj_m_tavishstop2
	global.__objectDepths[407] = -35; // obj_m_demo_sword
	global.__objectDepths[408] = 0; // obj_m_evadefight
	global.__objectDepths[409] = -3; // obj_m_fallsword
	global.__objectDepths[410] = 0; // obj_m_evadecheck
	global.__objectDepths[411] = 0; // obj_m_tavishstop3
	global.__objectDepths[412] = 0; // obj_m_noplatform
	global.__objectDepths[413] = -20; // obj_m_explosion
	global.__objectDepths[414] = -2500; // obj_m_falldowntext
	global.__objectDepths[415] = 0; // obj_m_tavishfall
	global.__objectDepths[416] = -31; // obj_m_shadow
	global.__objectDepths[417] = -35; // obj_m_zepheniah1
	global.__objectDepths[418] = 0; // obj_m_zepheniah2
	global.__objectDepths[419] = 0; // obj_m_puzzlebox
	global.__objectDepths[420] = 1; // obj_m_boxswitch
	global.__objectDepths[421] = 0; // obj_m_boxcheck1
	global.__objectDepths[422] = 0; // obj_m_boxcheck2
	global.__objectDepths[423] = 0; // obj_m_puzzledone
	global.__objectDepths[424] = 0; // obj_m_nobox
	global.__objectDepths[425] = 0; // obj_m_lever1
	global.__objectDepths[426] = 0; // obj_m_lever2
	global.__objectDepths[427] = 0; // obj_m_spikesup
	global.__objectDepths[428] = 0; // obj_m_spikesdown
	global.__objectDepths[429] = 0; // obj_m_tavishlast
	global.__objectDepths[430] = 0; // obj_m_laststop
	global.__objectDepths[431] = -1000; // obj_m_demowhite
	global.__objectDepths[432] = -1000; // obj_m_demowhiter
	global.__objectDepths[433] = -100; // obj_m_demoblink
	global.__objectDepths[434] = 0; // obj_m_startfight
	global.__objectDepths[435] = -10; // obj_m_demodrop
	global.__objectDepths[436] = -3; // obj_m_blackbattle
	global.__objectDepths[437] = 0; // obj_m_demowait
	global.__objectDepths[438] = 0; // obj_m_demochase
	global.__objectDepths[439] = 0; // obj_m_demobump
	global.__objectDepths[440] = 0; // obj_m_demodecide
	global.__objectDepths[441] = 0; // obj_m_floorsword2
	global.__objectDepths[442] = 0; // obj_m_chasespawn
	global.__objectDepths[443] = 0; // obj_m_demowall
	global.__objectDepths[444] = 0; // obj_m_demowait2
	global.__objectDepths[445] = 0; // obj_db_tavishtired
	global.__objectDepths[446] = 0; // obj_db_tiredtrigger
	global.__objectDepths[447] = 0; // obj_db_beercooler
	global.__objectDepths[448] = -31; // obj_db_drawbeer
	global.__objectDepths[449] = -5; // obj_db_pourbeer
	global.__objectDepths[450] = 1100000; // obj_green_goo
	global.__objectDepths[451] = -30; // obj_db_sniper_van
	global.__objectDepths[452] = 0; // obj_db_van_sniper3
	global.__objectDepths[453] = 0; // obj_db_van_sniper4
	global.__objectDepths[454] = 0; // obj_db_chimney
	global.__objectDepths[455] = -31; // obj_db_smallsmoke
	global.__objectDepths[456] = 0; // obj_db_duy
	global.__objectDepths[457] = 0; // obj_db_kid1
	global.__objectDepths[458] = 0; // obj_db_hissy
	global.__objectDepths[459] = 0; // obj_db_merc1
	global.__objectDepths[460] = 0; // obj_db_merc2
	global.__objectDepths[461] = 0; // obj_db_merc3
	global.__objectDepths[462] = 0; // obj_db_habana
	global.__objectDepths[463] = 0; // obj_db_spystop
	global.__objectDepths[464] = -35; // obj_db_turret
	global.__objectDepths[465] = 0; // obj_slippygoo
	global.__objectDepths[466] = 0; // obj_slippygoo_move
	global.__objectDepths[467] = 0; // obj_db_turretshoot
	global.__objectDepths[468] = -15; // obj_db_turretbullet
	global.__objectDepths[469] = 0; // obj_db_lever1
	global.__objectDepths[470] = 0; // obj_db_lever2
	global.__objectDepths[471] = 0; // obj_db_puzzlesolved
	global.__objectDepths[472] = 0; // obj_db_turrets1solved
	global.__objectDepths[473] = 0; // obj_db_elistop
	global.__objectDepths[474] = 0; // obj_db_eli1
	global.__objectDepths[475] = -15; // obj_db_exclamation
	global.__objectDepths[476] = -80; // obj_db_flash
	global.__objectDepths[477] = -2; // obj_db_disp1
	global.__objectDepths[478] = -2; // obj_db_disp2
	global.__objectDepths[479] = 2; // obj_db_kritz
	global.__objectDepths[480] = 5; // obj_db_eli_door
	global.__objectDepths[481] = -40; // obj_db_soulstart
	global.__objectDepths[482] = -40; // obj_db_soulgo
	global.__objectDepths[483] = -40; // obj_db_soulgo2
	global.__objectDepths[484] = -1000; // obj_db_call1
	global.__objectDepths[485] = -1000; // obj_db_call2
	global.__objectDepths[486] = -1000; // obj_db_call3
	global.__objectDepths[487] = -1000; // obj_db_call4
	global.__objectDepths[488] = -1000; // obj_db_call5
	global.__objectDepths[489] = -1000; // obj_db_call6
	global.__objectDepths[490] = -1000; // obj_db_call7
	global.__objectDepths[491] = -32; // obj_db_disp3
	global.__objectDepths[492] = -31; // obj_db_bowl
	global.__objectDepths[493] = 0; // obj_db_condiment
	global.__objectDepths[494] = 0; // obj_db_bundog
	global.__objectDepths[495] = 1; // obj_db_spikes1
	global.__objectDepths[496] = 1; // obj_db_spikes2
	global.__objectDepths[497] = 0; // obj_db_dispnote
	global.__objectDepths[498] = -2; // obj_db_disp4
	global.__objectDepths[499] = 0; // obj_db_getdog
	global.__objectDepths[500] = 0; // obj_db_mercs1
	global.__objectDepths[501] = 0; // obj_db_mercs2
	global.__objectDepths[502] = 0; // obj_db_mercs3
	global.__objectDepths[503] = -15; // obj_db_merc_ex
	global.__objectDepths[504] = -3; // obj_db_merctalk
	global.__objectDepths[505] = -5; // obj_db_mercs4
	global.__objectDepths[506] = 0; // obj_db_mercs5
	global.__objectDepths[507] = 0; // obj_db_mercencounters
	global.__objectDepths[508] = 5; // obj_db_cineback
	global.__objectDepths[509] = -35; // obj_db_cinecar
	global.__objectDepths[510] = -50; // obj_db_cinema
	global.__objectDepths[511] = -31; // obj_db_disp5
	global.__objectDepths[512] = -40; // obj_db_zombie1
	global.__objectDepths[513] = -40; // obj_db_zombie2
	global.__objectDepths[514] = -40; // obj_db_zombie3
	global.__objectDepths[515] = 0; // obj_db_ufo
	global.__objectDepths[516] = -32; // obj_db_bites
	global.__objectDepths[517] = 0; // obj_db_prostop
	global.__objectDepths[518] = -50; // obj_db_cinemadraw
	global.__objectDepths[519] = 0; // obj_db_spy
	global.__objectDepths[520] = 0; // obj_db_spystop1
	global.__objectDepths[521] = 0; // obj_db_spystop2
	global.__objectDepths[522] = 0; // obj_db_spystop3
	global.__objectDepths[523] = 0; // obj_db_spystop4
	global.__objectDepths[524] = 0; // obj_db_spystop5
	global.__objectDepths[525] = 0; // obj_db_spyintro
	global.__objectDepths[526] = 0; // obj_db_spyoutro
	global.__objectDepths[527] = 0; // obj_db_musical
	global.__objectDepths[528] = -35; // obj_db_disp6
	global.__objectDepths[529] = -31; // obj_theater_foreground
	global.__objectDepths[530] = -100; // obj_db_singsong
	global.__objectDepths[531] = -32; // obj_db_flybites
	global.__objectDepths[532] = 0; // obj_db_rose
	global.__objectDepths[533] = -32; // obj_db_glitter
	global.__objectDepths[534] = 0; // obj_mc_habdance
	global.__objectDepths[535] = 0; // obj_mc_wirt
	global.__objectDepths[536] = 0; // obj_mc_rickandmorty
	global.__objectDepths[537] = 0; // obj_mc_nass
	global.__objectDepths[538] = -5; // obj_mc_blinkdoor
	global.__objectDepths[539] = 0; // obj_mc_greg
	global.__objectDepths[540] = 0; // obj_mc_jason
	global.__objectDepths[541] = 1100000; // obj_cyan_goo
	global.__objectDepths[542] = 0; // obj_mc_lever1
	global.__objectDepths[543] = 0; // obj_mc_lever2
	global.__objectDepths[544] = 950000; // obj_mc_door
	global.__objectDepths[545] = 0; // obj_mc_switch1
	global.__objectDepths[546] = 0; // obj_mc_switch2
	global.__objectDepths[547] = 0; // obj_mc_switch3
	global.__objectDepths[548] = 0; // obj_mc_worker1
	global.__objectDepths[549] = 0; // obj_mc_worker2
	global.__objectDepths[550] = -15; // obj_mc_exclamation
	global.__objectDepths[551] = 0; // obj_mc_fleeprevention
	global.__objectDepths[552] = -1000; // obj_mc_call1
	global.__objectDepths[553] = -1000; // obj_mc_call2
	global.__objectDepths[554] = -1000; // obj_mc_call3
	global.__objectDepths[555] = -1000; // obj_mc_call4
	global.__objectDepths[556] = -1000; // obj_mc_call5
	global.__objectDepths[557] = 0; // obj_mc_disp1
	global.__objectDepths[558] = -2500; // obj_mc_whitescreen
	global.__objectDepths[559] = 0; // obj_mc_transformation
	global.__objectDepths[560] = -8; // obj_mc_scouttransform
	global.__objectDepths[561] = -5; // obj_mc_scoutsmoke
	global.__objectDepths[562] = -60; // obj_mc_transformwhite
	global.__objectDepths[563] = 0; // obj_mc_scout1
	global.__objectDepths[564] = 0; // obj_mc_scout2
	global.__objectDepths[565] = 0; // obj_mc_scoutblock
	global.__objectDepths[566] = 0; // obj_mc_dispenser_dead
	global.__objectDepths[567] = 0; // obj_mc_liftbutton
	global.__objectDepths[568] = 5; // obj_mc_eli1
	global.__objectDepths[569] = 2000000; // obj_mbm_parallax
	global.__objectDepths[570] = 0; // obj_mbm_vending
	global.__objectDepths[571] = 0; // obj_mbm_darkness
	global.__objectDepths[572] = 0; // obj_mbm_key1
	global.__objectDepths[573] = 0; // obj_mbm_key2
	global.__objectDepths[574] = -15; // obj_mbm_line
	global.__objectDepths[575] = 0; // obj_mbm_lockdoor
	global.__objectDepths[576] = -33; // obj_mbm_shadows
	global.__objectDepths[577] = -1000; // obj_mbm_call1
	global.__objectDepths[578] = -1000; // obj_mbm_call2
	global.__objectDepths[579] = -1000; // obj_mbm_call3
	global.__objectDepths[580] = -1000; // obj_mbm_call4
	global.__objectDepths[581] = -1000; // obj_mbm_call5
	global.__objectDepths[582] = -1000; // obj_mbm_call6
	global.__objectDepths[583] = -1000; // obj_mbm_call7
	global.__objectDepths[584] = 0; // obj_mbm_dell
	global.__objectDepths[585] = 0; // obj_mbm_dell2
	global.__objectDepths[586] = -30; // obj_mbm_dunk
	global.__objectDepths[587] = 0; // obj_mbm_sentry
	global.__objectDepths[588] = -35; // obj_mbm_exclamation
	global.__objectDepths[589] = 0; // obj_mbm_sentries
	global.__objectDepths[590] = 0; // obj_mbm_misha1
	global.__objectDepths[591] = -15; // obj_mbm_excl
	global.__objectDepths[592] = 0; // obj_mbm_misha2
	global.__objectDepths[593] = 0; // obj_mbm_misha3
	global.__objectDepths[594] = 0; // obj_misha_battle_intro
	global.__objectDepths[595] = -2500; // obj_mbm_whitescreen
	global.__objectDepths[596] = -20; // obj_mbm_mercy
	global.__objectDepths[597] = -100; // obj_mbm_death
	global.__objectDepths[598] = 0; // obj_mbm_bambam
	global.__objectDepths[599] = 0; // obj_mbm_dellcalls
	global.__objectDepths[600] = 0; // obj_mbm_ballooney
	global.__objectDepths[601] = 0; // obj_mbm_eli
	global.__objectDepths[602] = 0; // obj_mbm_pauling1
	global.__objectDepths[603] = 0; // obj_mbm_pauling2
	global.__objectDepths[604] = 0; // obj_mbm_pauling3
	global.__objectDepths[605] = 0; // obj_mbm_lastsoul
	global.__objectDepths[606] = -40; // obj_mbm_soul_battlestart
	global.__objectDepths[607] = -40; // obj_mbm_soul_tobattle
	global.__objectDepths[608] = -100; // obj_pl_evade_soul
	global.__objectDepths[609] = 0; // obj_pl_error
	global.__objectDepths[610] = 0; // obj_pl_ballooney1
	global.__objectDepths[611] = -40; // obj_pl_soulintro
	global.__objectDepths[612] = -40; // obj_pl_soulmove
	global.__objectDepths[613] = -120; // obj_pl_soulmove2
	global.__objectDepths[614] = -20; // obj_pl_pyro_intro
	global.__objectDepths[615] = -20; // obj_pl_pyro_intro2
	global.__objectDepths[616] = 0; // pyroweaponparent
	global.__objectDepths[617] = 0; // pyroattackparent
	global.__objectDepths[618] = -110; // obj_pl_gastank
	global.__objectDepths[619] = -100; // obj_pyro_fireball
	global.__objectDepths[620] = -115; // obj_pyro_fireball2
	global.__objectDepths[621] = -105; // obj_pl_flame
	global.__objectDepths[622] = -110; // obj_pl_flaregun
	global.__objectDepths[623] = -105; // obj_pl_flare
	global.__objectDepths[624] = 0; // obj_pl_flaregunspawn
	global.__objectDepths[625] = -108; // obj_pl_flareexhaust
	global.__objectDepths[626] = -112; // obj_pl_gas
	global.__objectDepths[627] = -110; // obj_pl_flamethrower
	global.__objectDepths[628] = -105; // obj_pl_rocket
	global.__objectDepths[629] = -110; // obj_pl_explode
	global.__objectDepths[630] = -115; // obj_pl_axe
	global.__objectDepths[631] = 0; // obj_pl_flamewaves
	global.__objectDepths[632] = 0; // obj_pl_flamewaves2
	global.__objectDepths[633] = -666; // obj_pl_hpandgun
	global.__objectDepths[634] = -90; // obj_pl_pyro_battle
	global.__objectDepths[635] = 2; // obj_pl_fight
	global.__objectDepths[636] = 0; // obj_pl_pyro_barrier
	global.__objectDepths[637] = 0; // obj_pl_pyro_barrier2
	global.__objectDepths[638] = -200; // obj_pl_damage_numbers
	global.__objectDepths[639] = -95; // obj_pl_whitenoise
	global.__objectDepths[640] = -10; // obj_pl_text_box
	global.__objectDepths[641] = 0; // balloonattackparent
	global.__objectDepths[642] = -5; // obj_pl_act
	global.__objectDepths[643] = -10; // obj_pl_helpbox
	global.__objectDepths[644] = 0; // obj_pl_balloonicorn1
	global.__objectDepths[645] = 0; // obj_pl_balloonicorn5
	global.__objectDepths[646] = 0; // obj_pl_balloonicorn6
	global.__objectDepths[647] = 0; // obj_pl_balloonicorn3
	global.__objectDepths[648] = 0; // obj_pl_balloonicorn4
	global.__objectDepths[649] = 0; // obj_pl_balloonicorn2
	global.__objectDepths[650] = -15; // obj_pl_tranquilizer
	global.__objectDepths[651] = -6; // obj_pl_crosshair
	global.__objectDepths[652] = -12; // obj_pl_tranqdart
	global.__objectDepths[653] = -6; // obj_pl_gear
	global.__objectDepths[654] = -15; // obj_pl_nail
	global.__objectDepths[655] = -15; // obj_pl_dynamite1
	global.__objectDepths[656] = -15; // obj_pl_dynamite2
	global.__objectDepths[657] = -15; // obj_pl_dynamite_saved
	global.__objectDepths[658] = -4; // obj_pl_boom
	global.__objectDepths[659] = -7; // obj_pl_rpg
	global.__objectDepths[660] = -15; // obj_pl_arrow
	global.__objectDepths[661] = -12; // obj_pl_bow
	global.__objectDepths[662] = -6; // obj_pl_rpgrocket
	global.__objectDepths[663] = 0; // obj_pl_b_finale
	global.__objectDepths[664] = -5; // obj_pl_f_balloonicorn
	global.__objectDepths[665] = -3; // obj_pl_f_balloonihelp
	global.__objectDepths[666] = 0; // obj_pl_pyrodeath
	global.__objectDepths[667] = -1000; // obj_pl_whitescreen
	global.__objectDepths[668] = -10; // obj_pl_finalpyro
	global.__objectDepths[669] = -5; // obj_pl_ballooney2
	global.__objectDepths[670] = -2500; // obj_pl_whitescreen2
	global.__objectDepths[671] = 0; // obj_th_fog
	global.__objectDepths[672] = 0; // obj_th_door
	global.__objectDepths[673] = -1000; // obj_th_call
	global.__objectDepths[674] = -1000; // obj_th_call2
	global.__objectDepths[675] = 0; // obj_th_note
	global.__objectDepths[676] = 0; // obj_th_liftblock
	global.__objectDepths[677] = -50; // obj_th_liftbuttons
	global.__objectDepths[678] = 0; // obj_th_terminal
	global.__objectDepths[679] = 0; // obj_th_door1
	global.__objectDepths[680] = 0; // obj_th_door2
	global.__objectDepths[681] = 0; // obj_th_liftbuttons2
	global.__objectDepths[682] = 0; // obj_th_key1
	global.__objectDepths[683] = -36; // obj_th_key1call
	global.__objectDepths[684] = -60; // obj_th_janegrip
	global.__objectDepths[685] = 0; // obj_th_key2
	global.__objectDepths[686] = 0; // obj_th_eli_portrait
	global.__objectDepths[687] = 0; // obj_th_key3
	global.__objectDepths[688] = 0; // obj_th_generator
	global.__objectDepths[689] = 0; // obj_tpe_misha1
	global.__objectDepths[690] = -5; // obj_tpe_syringe
	global.__objectDepths[691] = 5; // obj_tpe_sani1
	global.__objectDepths[692] = 0; // obj_tpe_misha2
	global.__objectDepths[693] = 0; // obj_tpe_demo
	global.__objectDepths[694] = -1; // obj_tpe_eli1
	global.__objectDepths[695] = 1; // obj_tpe_scout1
	global.__objectDepths[696] = -6; // obj_tpe_dell
	global.__objectDepths[697] = -5; // obj_tpe_jane
	global.__objectDepths[698] = -7; // obj_tpe_sniper
	global.__objectDepths[699] = -9; // obj_tpe_spy
	global.__objectDepths[700] = -5; // obj_tpe_ballooney1
	global.__objectDepths[701] = 0; // obj_tpe_saves
	global.__objectDepths[702] = 0; // obj_tpe_soul1
	global.__objectDepths[703] = -30; // obj_tpe_letter
	global.__objectDepths[704] = -8; // obj_endbox
	global.__objectDepths[705] = -8; // obj_tpe_gunsnmercs
	global.__objectDepths[706] = 0; // obj_tpe_flashback
	global.__objectDepths[707] = 100; // obj_tpe_background
	global.__objectDepths[708] = -9; // obj_tpe_ballooney2
	global.__objectDepths[709] = 0; // obj_tpe_mercs
	global.__objectDepths[710] = -5; // obj_tpe_evade_ground
	global.__objectDepths[711] = -30; // obj_tpe_soulmove
	global.__objectDepths[712] = -13; // obj_tpe_evade_soul
	global.__objectDepths[713] = -1000; // obj_tpe_death
	global.__objectDepths[714] = -10; // obj_tpe_danger_zones
	global.__objectDepths[715] = -20; // obj_tpe_misha_bullet
	global.__objectDepths[716] = 0; // obj_tpe_bullet_follow2
	global.__objectDepths[717] = -13; // obj_tpe_jar_drop
	global.__objectDepths[718] = -15; // obj_tpe_jar
	global.__objectDepths[719] = -15; // obj_tpe_crosshair
	global.__objectDepths[720] = -15; // obj_tpe_battle_bullet
	global.__objectDepths[721] = -4; // obj_tpe_blackscreen
	global.__objectDepths[722] = -15; // obj_tpe_bonesaw
	global.__objectDepths[723] = -17; // obj_tpe_syringe_gun
	global.__objectDepths[724] = -15; // obj_tpe_fight
	global.__objectDepths[725] = -15; // obj_tpe_finalgoodbye
	global.__objectDepths[726] = -5; // obj_tpe_finalballooney
	global.__objectDepths[727] = -30; // obj_tpe_outro1
	global.__objectDepths[728] = -20; // obj_tpe_outro2
	global.__objectDepths[729] = 0; // obj_tpe_dell2
	global.__objectDepths[730] = -3; // obj_tpe_jane2
	global.__objectDepths[731] = -5; // obj_tpe_demo2
	global.__objectDepths[732] = -6; // obj_tpe_eli2
	global.__objectDepths[733] = -7; // obj_tpe_misha3
	global.__objectDepths[734] = -8; // obj_tpe_sani2
	global.__objectDepths[735] = 0; // obj_tpe_cast1
	global.__objectDepths[736] = 5; // obj_tpe_cast2
	global.__objectDepths[737] = 0; // obj_tpe_cast3
	global.__objectDepths[738] = 5; // obj_tpe_cast4
	global.__objectDepths[739] = 5; // obj_tpe_cast5
	global.__objectDepths[740] = 5; // obj_tpe_cast6
	global.__objectDepths[741] = 0; // obj_tpe_cast7
	global.__objectDepths[742] = 10; // obj_tpe_castmember
	global.__objectDepths[743] = 0; // obj_tpe_photo
	global.__objectDepths[744] = 0; // obj_tpe_credits
	global.__objectDepths[745] = 0; // obj_tpe_special_mentions
	global.__objectDepths[746] = 0; // obj_tpe_richard
	global.__objectDepths[747] = 0; // obj_crowbar_item
	global.__objectDepths[748] = 0; // obj_syringe_item2
	global.__objectDepths[749] = 0; // obj_syringe_item1
	global.__objectDepths[750] = 0; // obj_jarate_item
	global.__objectDepths[751] = 0; // obj_sapper_item
	global.__objectDepths[752] = 0; // obj_intro_load_progress
	global.__objectDepths[753] = 0; // obj_name_input
	global.__objectDepths[754] = 0; // obj_controls
	global.__objectDepths[755] = 0; // obj_intro
	global.__objectDepths[756] = 0; // obj_main_menu
	global.__objectDepths[757] = -2500; // obj_intro_whitescreen
	global.__objectDepths[758] = 0; // obj_i_ballooney


	global.__objectNames[0] = "obj_global_variables";
	global.__objectNames[1] = "obj_gamevariables";
	global.__objectNames[2] = "obj_controller";
	global.__objectNames[3] = "obj_genocide_variables";
	global.__objectNames[4] = "obj_activation_object";
	global.__objectNames[5] = "obj_no_battle_zone";
	global.__objectNames[6] = "obj_wait_for_me";
	global.__objectNames[7] = "obj_music_player";
	global.__objectNames[8] = "obj_skip_room";
	global.__objectNames[9] = "obj_room_fade_out";
	global.__objectNames[10] = "obj_room_fade_in";
	global.__objectNames[11] = "obj_parallax_bg";
	global.__objectNames[12] = "obj_nobody_room";
	global.__objectNames[13] = "obj_game_saver";
	global.__objectNames[14] = "obj_store";
	global.__objectNames[15] = "obj_menu";
	global.__objectNames[16] = "obj_starttimer";
	global.__objectNames[17] = "obj_chat_activate";
	global.__objectNames[18] = "obj_chattest";
	global.__objectNames[19] = "obj_playtest_helper";
	global.__objectNames[20] = "oldbattlenpc";
	global.__objectNames[21] = "obj_old_player_scripts";
	global.__objectNames[22] = "obj_textbox_hunijkah";
	global.__objectNames[23] = "old_roomchange";
	global.__objectNames[24] = "old_textbox";
	global.__objectNames[25] = "oldobj_sven_battle";
	global.__objectNames[26] = "oldghostattack";
	global.__objectNames[27] = "OLDobj_sani_dummy";
	global.__objectNames[28] = "oldsyringegun";
	global.__objectNames[29] = "object246";
	global.__objectNames[30] = "OLDswordtest";
	global.__objectNames[31] = "oldconveyorbelt";
	global.__objectNames[32] = "OLDobj_merc_bullet";
	global.__objectNames[33] = "undynetest";
	global.__objectNames[34] = "olddispenserflying";
	global.__objectNames[35] = "crabtest";
	global.__objectNames[36] = "wizardtest";
	global.__objectNames[37] = "singtest";
	global.__objectNames[38] = "scouttest";
	global.__objectNames[39] = "gordontest";
	global.__objectNames[40] = "dispensertest";
	global.__objectNames[41] = "OLDobj_intro4";
	global.__objectNames[42] = "OLDobj_intro3";
	global.__objectNames[43] = "OLDobj_intro2";
	global.__objectNames[44] = "OLDgamevariables";
	global.__objectNames[45] = "OLDmishabody";
	global.__objectNames[46] = "obj_general_variables";
	global.__objectNames[47] = "OLDPyrotest";
	global.__objectNames[48] = "OLDobj_pl_soulmove2";
	global.__objectNames[49] = "OLDobj_pl_gear";
	global.__objectNames[50] = "OLDobj_pl_invisact1";
	global.__objectNames[51] = "OLDobj_pl_nail";
	global.__objectNames[52] = "OLDobj_pl_b_rocket";
	global.__objectNames[53] = "OLDnailcreator";
	global.__objectNames[54] = "oldpyrodrawgunandhp";
	global.__objectNames[55] = "delltest";
	global.__objectNames[56] = "object553";
	global.__objectNames[57] = "object577";
	global.__objectNames[58] = "killincreaser";
	global.__objectNames[59] = "countertest";
	global.__objectNames[60] = "EVADETIMESKIP";
	global.__objectNames[61] = "Kittentest";
	global.__objectNames[62] = "object754";
	global.__objectNames[63] = "object721";
	global.__objectNames[64] = "calltester";
	global.__objectNames[65] = "obj_camera";
	global.__objectNames[66] = "obj_solid";
	global.__objectNames[67] = "obj_talk_object";
	global.__objectNames[68] = "obj_roomchange";
	global.__objectNames[69] = "obj_protagonist";
	global.__objectNames[70] = "obj_npc1";
	global.__objectNames[71] = "obj_view_parent";
	global.__objectNames[72] = "obj_save";
	global.__objectNames[73] = "obj_apple";
	global.__objectNames[74] = "obj_player_spawn";
	global.__objectNames[75] = "obj_switch_template";
	global.__objectNames[76] = "obj_text_box";
	global.__objectNames[77] = "obj_text_box_battle";
	global.__objectNames[78] = "obj_nobody_textbox";
	global.__objectNames[79] = "obj_text_box_battle_end";
	global.__objectNames[80] = "obj_speech_bubble";
	global.__objectNames[81] = "obj_speech_bubble_noevade";
	global.__objectNames[82] = "obj_textbox_death";
	global.__objectNames[83] = "obj_textbox_item";
	global.__objectNames[84] = "obj_save_box";
	global.__objectNames[85] = "obj_text_box_misha";
	global.__objectNames[86] = "obj_textface";
	global.__objectNames[87] = "obj_com_exclamation";
	global.__objectNames[88] = "obj_soul_battlestart";
	global.__objectNames[89] = "obj_blackscreen";
	global.__objectNames[90] = "obj_soul_tobattle";
	global.__objectNames[91] = "obj_soul_fadebattle";
	global.__objectNames[92] = "obj_battle_bg";
	global.__objectNames[93] = "obj_battle_gui";
	global.__objectNames[94] = "obj_soul_battle_select";
	global.__objectNames[95] = "obj_battle_ground";
	global.__objectNames[96] = "obj_battle_enemy_select";
	global.__objectNames[97] = "obj_target_choice";
	global.__objectNames[98] = "obj_damaging_enemy";
	global.__objectNames[99] = "obj_check_up";
	global.__objectNames[100] = "obj_enemy_down";
	global.__objectNames[101] = "obj_enemy_spared";
	global.__objectNames[102] = "obj_enemy_spareable";
	global.__objectNames[103] = "obj_enemy2_checkup";
	global.__objectNames[104] = "obj_enemy1_checkup";
	global.__objectNames[105] = "obj_enemy3_checkup";
	global.__objectNames[106] = "obj_box_to_evade";
	global.__objectNames[107] = "obj_evade_ground";
	global.__objectNames[108] = "obj_evade_to_box";
	global.__objectNames[109] = "obj_evade_soul";
	global.__objectNames[110] = "obj_soul_ball";
	global.__objectNames[111] = "obj_evade_shield";
	global.__objectNames[112] = "obj_act_enemy_select";
	global.__objectNames[113] = "obj_youact";
	global.__objectNames[114] = "obj_soul_flee";
	global.__objectNames[115] = "obj_fleedecide";
	global.__objectNames[116] = "obj_battle_death";
	global.__objectNames[117] = "obj_soul_bits";
	global.__objectNames[118] = "obj_bit1";
	global.__objectNames[119] = "obj_bit2";
	global.__objectNames[120] = "obj_bit3";
	global.__objectNames[121] = "obj_bit4";
	global.__objectNames[122] = "obj_gameover_message";
	global.__objectNames[123] = "obj_death_effect";
	global.__objectNames[124] = "obj_spare_effect";
	global.__objectNames[125] = "obj_sparedust";
	global.__objectNames[126] = "obj_deathflames";
	global.__objectNames[127] = "obj_miss";
	global.__objectNames[128] = "obj_crit";
	global.__objectNames[129] = "obj_betrayal_kill";
	global.__objectNames[130] = "obj_damage_numbers";
	global.__objectNames[131] = "obj_jarate_effect";
	global.__objectNames[132] = "obj_jarate_drop";
	global.__objectNames[133] = "obj_battle_fade_out";
	global.__objectNames[134] = "obj_fightwave";
	global.__objectNames[135] = "obj_actwave";
	global.__objectNames[136] = "obj_itemwave";
	global.__objectNames[137] = "obj_sparewave";
	global.__objectNames[138] = "obj_fleewave";
	global.__objectNames[139] = "obj_battlenpc_parent";
	global.__objectNames[140] = "obj_enemy_attack_parent";
	global.__objectNames[141] = "obj_battlenpc_1";
	global.__objectNames[142] = "obj_bullet_test";
	global.__objectNames[143] = "obj_sven_battle";
	global.__objectNames[144] = "obj_sven_saw_hor";
	global.__objectNames[145] = "obj_sven_saw_hor2";
	global.__objectNames[146] = "obj_sven_saw_vert";
	global.__objectNames[147] = "obj_ccat_battle";
	global.__objectNames[148] = "obj_ccat_tear";
	global.__objectNames[149] = "obj_sani_dummy";
	global.__objectNames[150] = "obj_zeph_battle";
	global.__objectNames[151] = "obj_ghost_attack";
	global.__objectNames[152] = "obj_sani_battle";
	global.__objectNames[153] = "obj_sani_bonesaw";
	global.__objectNames[154] = "obj_sani_needle";
	global.__objectNames[155] = "obj_sani_syringe_gun";
	global.__objectNames[156] = "obj_sniper_battle";
	global.__objectNames[157] = "obj_tm_battle_bullet";
	global.__objectNames[158] = "obj_tm_jar_shard";
	global.__objectNames[159] = "obj_tm_jar";
	global.__objectNames[160] = "obj_tm_jar_drop";
	global.__objectNames[161] = "obj_tm_crosshair";
	global.__objectNames[162] = "obj_tm_battle_bullet2";
	global.__objectNames[163] = "obj_magpie_battle";
	global.__objectNames[164] = "obj_magpie_feather";
	global.__objectNames[165] = "obj_greater_birb";
	global.__objectNames[166] = "obj_small_birb";
	global.__objectNames[167] = "obj_jane_battle";
	global.__objectNames[168] = "obj_jane_rocket";
	global.__objectNames[169] = "obj_jane_head";
	global.__objectNames[170] = "obj_bites_battle";
	global.__objectNames[171] = "obj_jane_extra_box";
	global.__objectNames[172] = "obj_tavish_battle";
	global.__objectNames[173] = "obj_m_demointro";
	global.__objectNames[174] = "obj_tavish_swordpiece";
	global.__objectNames[175] = "obj_m_risesword";
	global.__objectNames[176] = "obj_m_whitescreen";
	global.__objectNames[177] = "obj_cackle_battle";
	global.__objectNames[178] = "obj_cackle_fire";
	global.__objectNames[179] = "obj_miniculus_battle";
	global.__objectNames[180] = "obj_miniculus_eye";
	global.__objectNames[181] = "obj_merc1_battle";
	global.__objectNames[182] = "obj_merc2_battle";
	global.__objectNames[183] = "obj_merc3_battle";
	global.__objectNames[184] = "obj_spy_battle";
	global.__objectNames[185] = "obj_smoke_spawn";
	global.__objectNames[186] = "obj_spy_crab";
	global.__objectNames[187] = "obj_spy_smoke";
	global.__objectNames[188] = "obj_slacker_battle";
	global.__objectNames[189] = "obj_slacker_knife";
	global.__objectNames[190] = "obj_stan_battle";
	global.__objectNames[191] = "obj_stan_question";
	global.__objectNames[192] = "obj_wizard_battle";
	global.__objectNames[193] = "obj_wizard_thunder";
	global.__objectNames[194] = "obj_wizard_hand";
	global.__objectNames[195] = "obj_physician_battle";
	global.__objectNames[196] = "obj_physician_crowbar";
	global.__objectNames[197] = "obj_dispenser_battle";
	global.__objectNames[198] = "obj_tiny_dispenser";
	global.__objectNames[199] = "obj_tiny_dispenser2";
	global.__objectNames[200] = "obj_tiny_disp_bolt";
	global.__objectNames[201] = "obj_tiny_block";
	global.__objectNames[202] = "obj_mc_tinyball";
	global.__objectNames[203] = "obj_mc_tinydisp";
	global.__objectNames[204] = "obj_scout_battle";
	global.__objectNames[205] = "obj_scout_legattack";
	global.__objectNames[206] = "obj_misha_battle";
	global.__objectNames[207] = "obj_bullet_follow";
	global.__objectNames[208] = "obj_bullet_follow2";
	global.__objectNames[209] = "obj_misha_punchmode";
	global.__objectNames[210] = "obj_heavy_eye";
	global.__objectNames[211] = "obj_misha_punch";
	global.__objectNames[212] = "obj_misha_punch2";
	global.__objectNames[213] = "obj_misha_bullet";
	global.__objectNames[214] = "obj_danger_zones";
	global.__objectNames[215] = "obj_misha_death";
	global.__objectNames[216] = "obj_misha_heart";
	global.__objectNames[217] = "obj_misha_heartbit";
	global.__objectNames[218] = "obj_misha_lastbox";
	global.__objectNames[219] = "obj_misha_fightchoice";
	global.__objectNames[220] = "obj_misha_mercychoice";
	global.__objectNames[221] = "obj_misha_bottle";
	global.__objectNames[222] = "obj_misha_bottle_shards";
	global.__objectNames[223] = "obj_mbm_dell_intro";
	global.__objectNames[224] = "obj_dell_battle";
	global.__objectNames[225] = "obj_dell_box";
	global.__objectNames[226] = "obj_frontier_justice";
	global.__objectNames[227] = "obj_justice_blast";
	global.__objectNames[228] = "obj_dell_platform";
	global.__objectNames[229] = "obj_dell_wrench";
	global.__objectNames[230] = "obj_dell_sidewrench";
	global.__objectNames[231] = "obj_battle_bleeding";
	global.__objectNames[232] = "obj_dell_sparefadeout";
	global.__objectNames[233] = "obj_dell_extrasoul";
	global.__objectNames[234] = "obj_dell_wrenchloop";
	global.__objectNames[235] = "obj_dell_wrenchfight";
	global.__objectNames[236] = "obj_dell_handattack";
	global.__objectNames[237] = "obj_mbm_tele";
	global.__objectNames[238] = "obj_dell_battle_sentry";
	global.__objectNames[239] = "obj_dell_bullet";
	global.__objectNames[240] = "obj_dell_evade_wall";
	global.__objectNames[241] = "obj_dell_phasethree";
	global.__objectNames[242] = "obj_dell_evade_floor";
	global.__objectNames[243] = "obj_dell_extraground";
	global.__objectNames[244] = "obj_dell_whitescreen";
	global.__objectNames[245] = "obj_dell_item";
	global.__objectNames[246] = "obj_dell_death";
	global.__objectNames[247] = "obj_dell_z";
	global.__objectNames[248] = "obj_eli_battle";
	global.__objectNames[249] = "obj_eli_battle_heals";
	global.__objectNames[250] = "obj_lethal_battle";
	global.__objectNames[251] = "obj_lethal_jaws";
	global.__objectNames[252] = "obj_hurts_battle";
	global.__objectNames[253] = "obj_ithurts_blade";
	global.__objectNames[254] = "obj_ithurts_bladepiece";
	global.__objectNames[255] = "obj_hunter_battle";
	global.__objectNames[256] = "obj_hunter_arm";
	global.__objectNames[257] = "obj_fake_soul_battlestart";
	global.__objectNames[258] = "obj_fake_soul_tobattle";
	global.__objectNames[259] = "obj_fake_blackscreen";
	global.__objectNames[260] = "obj_fake_evade_ground";
	global.__objectNames[261] = "obj_fake_evade_soul";
	global.__objectNames[262] = "obj_fake_soul_fadebattle";
	global.__objectNames[263] = "obj_fake_battle_fade_out";
	global.__objectNames[264] = "obj_pro_stopped";
	global.__objectNames[265] = "obj_path_left";
	global.__objectNames[266] = "obj_h_ballooney1";
	global.__objectNames[267] = "obj_ballooney_fake_battle";
	global.__objectNames[268] = "obj_h_beer_bottle";
	global.__objectNames[269] = "obj_h_beer_bottle_fly";
	global.__objectNames[270] = "obj_h_beer_bottle_shard";
	global.__objectNames[271] = "obj_h_whitescreen";
	global.__objectNames[272] = "obj_h_soul_arrows";
	global.__objectNames[273] = "obj_sani1_moving";
	global.__objectNames[274] = "obj_sani_encounter_stop";
	global.__objectNames[275] = "obj_sani1_exc";
	global.__objectNames[276] = "obj_h_switch1";
	global.__objectNames[277] = "obj_h_spike1";
	global.__objectNames[278] = "obj_h_spike1_down";
	global.__objectNames[279] = "obj_sani2_wait";
	global.__objectNames[280] = "obj_sani3_wait";
	global.__objectNames[281] = "obj_h_dummy";
	global.__objectNames[282] = "obj_sani4_stand";
	global.__objectNames[283] = "obj_sani5_stand";
	global.__objectNames[284] = "obj_sani6_stand";
	global.__objectNames[285] = "obj_sani7_wait";
	global.__objectNames[286] = "obj_h_runspikes_down";
	global.__objectNames[287] = "obj_h_runspikes_up";
	global.__objectNames[288] = "obj_h_habana";
	global.__objectNames[289] = "obj_h_easter_egg";
	global.__objectNames[290] = "obj_h_zepheniah_floor";
	global.__objectNames[291] = "obj_h_zepheniah_after";
	global.__objectNames[292] = "obj_h_number_button";
	global.__objectNames[293] = "obj_h_number_spikes_up";
	global.__objectNames[294] = "obj_h_number_spikes_down";
	global.__objectNames[295] = "obj_h_number_check1";
	global.__objectNames[296] = "obj_h_number_lever";
	global.__objectNames[297] = "obj_h_number_lever_2";
	global.__objectNames[298] = "obj_h_number_check2";
	global.__objectNames[299] = "obj_sani8_stand";
	global.__objectNames[300] = "obj_sani8_exc";
	global.__objectNames[301] = "obj_sani8_stop";
	global.__objectNames[302] = "obj_medigun_machine";
	global.__objectNames[303] = "obj_noleave";
	global.__objectNames[304] = "obj_sani9_rush";
	global.__objectNames[305] = "obj_sani10_wait";
	global.__objectNames[306] = "obj_sani11_to_surgery";
	global.__objectNames[307] = "obj_sani12_surgery";
	global.__objectNames[308] = "obj_h_target";
	global.__objectNames[309] = "obj_h_medi_beam";
	global.__objectNames[310] = "obj_sani13";
	global.__objectNames[311] = "obj_sani14_leave";
	global.__objectNames[312] = "obj_h_flee_spikes_down";
	global.__objectNames[313] = "obj_h_flee_spikes_up";
	global.__objectNames[314] = "obj_sani_h_goodbye";
	global.__objectNames[315] = "obj_h_dove";
	global.__objectNames[316] = "obj_h_ballooney2";
	global.__objectNames[317] = "obj_h_leaving";
	global.__objectNames[318] = "obj_h_whitescreen2";
	global.__objectNames[319] = "obj_h_bambam";
	global.__objectNames[320] = "obj_tm_sentry1";
	global.__objectNames[321] = "obj_sentry_exc";
	global.__objectNames[322] = "obj_tm_dell1";
	global.__objectNames[323] = "obj_tm_jane1";
	global.__objectNames[324] = "obj_tm_jane2";
	global.__objectNames[325] = "obj_tm_dell2";
	global.__objectNames[326] = "obj_tm_dell3";
	global.__objectNames[327] = "obj_tm_jane3";
	global.__objectNames[328] = "obj_tm_grenade";
	global.__objectNames[329] = "obj_tm_grenade_blink";
	global.__objectNames[330] = "obj_tm_explosion";
	global.__objectNames[331] = "obj_tm_wall_stop";
	global.__objectNames[332] = "obj_tm_wall_noreturn1";
	global.__objectNames[333] = "obj_tm_water_cooler";
	global.__objectNames[334] = "obj_tm_habana";
	global.__objectNames[335] = "obj_tm_bunnies";
	global.__objectNames[336] = "obj_tm_fox";
	global.__objectNames[337] = "obj_tm_dispenser";
	global.__objectNames[338] = "obj_tm_mine";
	global.__objectNames[339] = "obj_tm_mine_stop";
	global.__objectNames[340] = "obj_tm_jane4";
	global.__objectNames[341] = "obj_tm_wall_noreturn2";
	global.__objectNames[342] = "obj_tm_jane5";
	global.__objectNames[343] = "obj_tm_dell4";
	global.__objectNames[344] = "obj_tm_dell5";
	global.__objectNames[345] = "obj_tm_wall_noreturn3";
	global.__objectNames[346] = "obj_tm_sniperstop";
	global.__objectNames[347] = "obj_tm_sniperstop2";
	global.__objectNames[348] = "obj_tm_spikebutton";
	global.__objectNames[349] = "obj_tm_spikes1_down";
	global.__objectNames[350] = "obj_tm_spikes1_up";
	global.__objectNames[351] = "obj_tm_spikes2_up";
	global.__objectNames[352] = "obj_tm_spikes3_up";
	global.__objectNames[353] = "obj_tm_spikes3_down";
	global.__objectNames[354] = "obj_tm_spikes2_down";
	global.__objectNames[355] = "obj_tm_sniper_torso";
	global.__objectNames[356] = "obj_tm_sniper_torso2";
	global.__objectNames[357] = "obj_tm_sniper_torso3";
	global.__objectNames[358] = "obj_tm_sniper_talk";
	global.__objectNames[359] = "obj_tm_sniper_laser1";
	global.__objectNames[360] = "obj_tm_sniper_laser2";
	global.__objectNames[361] = "obj_tm_sniper_torso_rifle";
	global.__objectNames[362] = "obj_tm_sniper_torso_rifle2";
	global.__objectNames[363] = "obj_tm_sniper_bullet";
	global.__objectNames[364] = "obj_tm_sniper_bullet2";
	global.__objectNames[365] = "obj_tm_hereitcomes";
	global.__objectNames[366] = "obj_tm_sniper_shooting";
	global.__objectNames[367] = "obj_tm_dell6";
	global.__objectNames[368] = "obj_tm_van_sniper";
	global.__objectNames[369] = "obj_tm_sniper_van";
	global.__objectNames[370] = "lasertest";
	global.__objectNames[371] = "obj_sniperdot";
	global.__objectNames[372] = "obj_db_van_sniper2";
	global.__objectNames[373] = "obj_db_cakebomb";
	global.__objectNames[374] = "obj_db_teufortians";
	global.__objectNames[375] = "obj_db_dell";
	global.__objectNames[376] = "obj_db_jane1";
	global.__objectNames[377] = "obj_db_jane2";
	global.__objectNames[378] = "obj_fake_jane_battle";
	global.__objectNames[379] = "obj_battle_spraycan";
	global.__objectNames[380] = "obj_battle_spray";
	global.__objectNames[381] = "obj_db_trashcan";
	global.__objectNames[382] = "obj_db_housebites";
	global.__objectNames[383] = "obj_db_housejane";
	global.__objectNames[384] = "obj_db_housearmor";
	global.__objectNames[385] = "obj_db_housetavish";
	global.__objectNames[386] = "obj_db_housedell";
	global.__objectNames[387] = "obj_m_dell";
	global.__objectNames[388] = "obj_m_tallgrass";
	global.__objectNames[389] = "obj_m_waterfall";
	global.__objectNames[390] = "obj_minecart";
	global.__objectNames[391] = "obj_m_habana";
	global.__objectNames[392] = "obj_m_miner";
	global.__objectNames[393] = "obj_m_canary";
	global.__objectNames[394] = "obj_m_canary2";
	global.__objectNames[395] = "obj_m_mouse";
	global.__objectNames[396] = "obj_m_dell2";
	global.__objectNames[397] = "obj_m_dell3";
	global.__objectNames[398] = "obj_m_call1";
	global.__objectNames[399] = "obj_m_call2";
	global.__objectNames[400] = "obj_m_call3";
	global.__objectNames[401] = "obj_m_tavishstop1";
	global.__objectNames[402] = "obj_m_tavish1";
	global.__objectNames[403] = "obj_m_jane";
	global.__objectNames[404] = "obj_m_tavishcart";
	global.__objectNames[405] = "obj_m_floorsword";
	global.__objectNames[406] = "obj_m_tavishstop2";
	global.__objectNames[407] = "obj_m_demo_sword";
	global.__objectNames[408] = "obj_m_evadefight";
	global.__objectNames[409] = "obj_m_fallsword";
	global.__objectNames[410] = "obj_m_evadecheck";
	global.__objectNames[411] = "obj_m_tavishstop3";
	global.__objectNames[412] = "obj_m_noplatform";
	global.__objectNames[413] = "obj_m_explosion";
	global.__objectNames[414] = "obj_m_falldowntext";
	global.__objectNames[415] = "obj_m_tavishfall";
	global.__objectNames[416] = "obj_m_shadow";
	global.__objectNames[417] = "obj_m_zepheniah1";
	global.__objectNames[418] = "obj_m_zepheniah2";
	global.__objectNames[419] = "obj_m_puzzlebox";
	global.__objectNames[420] = "obj_m_boxswitch";
	global.__objectNames[421] = "obj_m_boxcheck1";
	global.__objectNames[422] = "obj_m_boxcheck2";
	global.__objectNames[423] = "obj_m_puzzledone";
	global.__objectNames[424] = "obj_m_nobox";
	global.__objectNames[425] = "obj_m_lever1";
	global.__objectNames[426] = "obj_m_lever2";
	global.__objectNames[427] = "obj_m_spikesup";
	global.__objectNames[428] = "obj_m_spikesdown";
	global.__objectNames[429] = "obj_m_tavishlast";
	global.__objectNames[430] = "obj_m_laststop";
	global.__objectNames[431] = "obj_m_demowhite";
	global.__objectNames[432] = "obj_m_demowhiter";
	global.__objectNames[433] = "obj_m_demoblink";
	global.__objectNames[434] = "obj_m_startfight";
	global.__objectNames[435] = "obj_m_demodrop";
	global.__objectNames[436] = "obj_m_blackbattle";
	global.__objectNames[437] = "obj_m_demowait";
	global.__objectNames[438] = "obj_m_demochase";
	global.__objectNames[439] = "obj_m_demobump";
	global.__objectNames[440] = "obj_m_demodecide";
	global.__objectNames[441] = "obj_m_floorsword2";
	global.__objectNames[442] = "obj_m_chasespawn";
	global.__objectNames[443] = "obj_m_demowall";
	global.__objectNames[444] = "obj_m_demowait2";
	global.__objectNames[445] = "obj_db_tavishtired";
	global.__objectNames[446] = "obj_db_tiredtrigger";
	global.__objectNames[447] = "obj_db_beercooler";
	global.__objectNames[448] = "obj_db_drawbeer";
	global.__objectNames[449] = "obj_db_pourbeer";
	global.__objectNames[450] = "obj_green_goo";
	global.__objectNames[451] = "obj_db_sniper_van";
	global.__objectNames[452] = "obj_db_van_sniper3";
	global.__objectNames[453] = "obj_db_van_sniper4";
	global.__objectNames[454] = "obj_db_chimney";
	global.__objectNames[455] = "obj_db_smallsmoke";
	global.__objectNames[456] = "obj_db_duy";
	global.__objectNames[457] = "obj_db_kid1";
	global.__objectNames[458] = "obj_db_hissy";
	global.__objectNames[459] = "obj_db_merc1";
	global.__objectNames[460] = "obj_db_merc2";
	global.__objectNames[461] = "obj_db_merc3";
	global.__objectNames[462] = "obj_db_habana";
	global.__objectNames[463] = "obj_db_spystop";
	global.__objectNames[464] = "obj_db_turret";
	global.__objectNames[465] = "obj_slippygoo";
	global.__objectNames[466] = "obj_slippygoo_move";
	global.__objectNames[467] = "obj_db_turretshoot";
	global.__objectNames[468] = "obj_db_turretbullet";
	global.__objectNames[469] = "obj_db_lever1";
	global.__objectNames[470] = "obj_db_lever2";
	global.__objectNames[471] = "obj_db_puzzlesolved";
	global.__objectNames[472] = "obj_db_turrets1solved";
	global.__objectNames[473] = "obj_db_elistop";
	global.__objectNames[474] = "obj_db_eli1";
	global.__objectNames[475] = "obj_db_exclamation";
	global.__objectNames[476] = "obj_db_flash";
	global.__objectNames[477] = "obj_db_disp1";
	global.__objectNames[478] = "obj_db_disp2";
	global.__objectNames[479] = "obj_db_kritz";
	global.__objectNames[480] = "obj_db_eli_door";
	global.__objectNames[481] = "obj_db_soulstart";
	global.__objectNames[482] = "obj_db_soulgo";
	global.__objectNames[483] = "obj_db_soulgo2";
	global.__objectNames[484] = "obj_db_call1";
	global.__objectNames[485] = "obj_db_call2";
	global.__objectNames[486] = "obj_db_call3";
	global.__objectNames[487] = "obj_db_call4";
	global.__objectNames[488] = "obj_db_call5";
	global.__objectNames[489] = "obj_db_call6";
	global.__objectNames[490] = "obj_db_call7";
	global.__objectNames[491] = "obj_db_disp3";
	global.__objectNames[492] = "obj_db_bowl";
	global.__objectNames[493] = "obj_db_condiment";
	global.__objectNames[494] = "obj_db_bundog";
	global.__objectNames[495] = "obj_db_spikes1";
	global.__objectNames[496] = "obj_db_spikes2";
	global.__objectNames[497] = "obj_db_dispnote";
	global.__objectNames[498] = "obj_db_disp4";
	global.__objectNames[499] = "obj_db_getdog";
	global.__objectNames[500] = "obj_db_mercs1";
	global.__objectNames[501] = "obj_db_mercs2";
	global.__objectNames[502] = "obj_db_mercs3";
	global.__objectNames[503] = "obj_db_merc_ex";
	global.__objectNames[504] = "obj_db_merctalk";
	global.__objectNames[505] = "obj_db_mercs4";
	global.__objectNames[506] = "obj_db_mercs5";
	global.__objectNames[507] = "obj_db_mercencounters";
	global.__objectNames[508] = "obj_db_cineback";
	global.__objectNames[509] = "obj_db_cinecar";
	global.__objectNames[510] = "obj_db_cinema";
	global.__objectNames[511] = "obj_db_disp5";
	global.__objectNames[512] = "obj_db_zombie1";
	global.__objectNames[513] = "obj_db_zombie2";
	global.__objectNames[514] = "obj_db_zombie3";
	global.__objectNames[515] = "obj_db_ufo";
	global.__objectNames[516] = "obj_db_bites";
	global.__objectNames[517] = "obj_db_prostop";
	global.__objectNames[518] = "obj_db_cinemadraw";
	global.__objectNames[519] = "obj_db_spy";
	global.__objectNames[520] = "obj_db_spystop1";
	global.__objectNames[521] = "obj_db_spystop2";
	global.__objectNames[522] = "obj_db_spystop3";
	global.__objectNames[523] = "obj_db_spystop4";
	global.__objectNames[524] = "obj_db_spystop5";
	global.__objectNames[525] = "obj_db_spyintro";
	global.__objectNames[526] = "obj_db_spyoutro";
	global.__objectNames[527] = "obj_db_musical";
	global.__objectNames[528] = "obj_db_disp6";
	global.__objectNames[529] = "obj_theater_foreground";
	global.__objectNames[530] = "obj_db_singsong";
	global.__objectNames[531] = "obj_db_flybites";
	global.__objectNames[532] = "obj_db_rose";
	global.__objectNames[533] = "obj_db_glitter";
	global.__objectNames[534] = "obj_mc_habdance";
	global.__objectNames[535] = "obj_mc_wirt";
	global.__objectNames[536] = "obj_mc_rickandmorty";
	global.__objectNames[537] = "obj_mc_nass";
	global.__objectNames[538] = "obj_mc_blinkdoor";
	global.__objectNames[539] = "obj_mc_greg";
	global.__objectNames[540] = "obj_mc_jason";
	global.__objectNames[541] = "obj_cyan_goo";
	global.__objectNames[542] = "obj_mc_lever1";
	global.__objectNames[543] = "obj_mc_lever2";
	global.__objectNames[544] = "obj_mc_door";
	global.__objectNames[545] = "obj_mc_switch1";
	global.__objectNames[546] = "obj_mc_switch2";
	global.__objectNames[547] = "obj_mc_switch3";
	global.__objectNames[548] = "obj_mc_worker1";
	global.__objectNames[549] = "obj_mc_worker2";
	global.__objectNames[550] = "obj_mc_exclamation";
	global.__objectNames[551] = "obj_mc_fleeprevention";
	global.__objectNames[552] = "obj_mc_call1";
	global.__objectNames[553] = "obj_mc_call2";
	global.__objectNames[554] = "obj_mc_call3";
	global.__objectNames[555] = "obj_mc_call4";
	global.__objectNames[556] = "obj_mc_call5";
	global.__objectNames[557] = "obj_mc_disp1";
	global.__objectNames[558] = "obj_mc_whitescreen";
	global.__objectNames[559] = "obj_mc_transformation";
	global.__objectNames[560] = "obj_mc_scouttransform";
	global.__objectNames[561] = "obj_mc_scoutsmoke";
	global.__objectNames[562] = "obj_mc_transformwhite";
	global.__objectNames[563] = "obj_mc_scout1";
	global.__objectNames[564] = "obj_mc_scout2";
	global.__objectNames[565] = "obj_mc_scoutblock";
	global.__objectNames[566] = "obj_mc_dispenser_dead";
	global.__objectNames[567] = "obj_mc_liftbutton";
	global.__objectNames[568] = "obj_mc_eli1";
	global.__objectNames[569] = "obj_mbm_parallax";
	global.__objectNames[570] = "obj_mbm_vending";
	global.__objectNames[571] = "obj_mbm_darkness";
	global.__objectNames[572] = "obj_mbm_key1";
	global.__objectNames[573] = "obj_mbm_key2";
	global.__objectNames[574] = "obj_mbm_line";
	global.__objectNames[575] = "obj_mbm_lockdoor";
	global.__objectNames[576] = "obj_mbm_shadows";
	global.__objectNames[577] = "obj_mbm_call1";
	global.__objectNames[578] = "obj_mbm_call2";
	global.__objectNames[579] = "obj_mbm_call3";
	global.__objectNames[580] = "obj_mbm_call4";
	global.__objectNames[581] = "obj_mbm_call5";
	global.__objectNames[582] = "obj_mbm_call6";
	global.__objectNames[583] = "obj_mbm_call7";
	global.__objectNames[584] = "obj_mbm_dell";
	global.__objectNames[585] = "obj_mbm_dell2";
	global.__objectNames[586] = "obj_mbm_dunk";
	global.__objectNames[587] = "obj_mbm_sentry";
	global.__objectNames[588] = "obj_mbm_exclamation";
	global.__objectNames[589] = "obj_mbm_sentries";
	global.__objectNames[590] = "obj_mbm_misha1";
	global.__objectNames[591] = "obj_mbm_excl";
	global.__objectNames[592] = "obj_mbm_misha2";
	global.__objectNames[593] = "obj_mbm_misha3";
	global.__objectNames[594] = "obj_misha_battle_intro";
	global.__objectNames[595] = "obj_mbm_whitescreen";
	global.__objectNames[596] = "obj_mbm_mercy";
	global.__objectNames[597] = "obj_mbm_death";
	global.__objectNames[598] = "obj_mbm_bambam";
	global.__objectNames[599] = "obj_mbm_dellcalls";
	global.__objectNames[600] = "obj_mbm_ballooney";
	global.__objectNames[601] = "obj_mbm_eli";
	global.__objectNames[602] = "obj_mbm_pauling1";
	global.__objectNames[603] = "obj_mbm_pauling2";
	global.__objectNames[604] = "obj_mbm_pauling3";
	global.__objectNames[605] = "obj_mbm_lastsoul";
	global.__objectNames[606] = "obj_mbm_soul_battlestart";
	global.__objectNames[607] = "obj_mbm_soul_tobattle";
	global.__objectNames[608] = "obj_pl_evade_soul";
	global.__objectNames[609] = "obj_pl_error";
	global.__objectNames[610] = "obj_pl_ballooney1";
	global.__objectNames[611] = "obj_pl_soulintro";
	global.__objectNames[612] = "obj_pl_soulmove";
	global.__objectNames[613] = "obj_pl_soulmove2";
	global.__objectNames[614] = "obj_pl_pyro_intro";
	global.__objectNames[615] = "obj_pl_pyro_intro2";
	global.__objectNames[616] = "pyroweaponparent";
	global.__objectNames[617] = "pyroattackparent";
	global.__objectNames[618] = "obj_pl_gastank";
	global.__objectNames[619] = "obj_pyro_fireball";
	global.__objectNames[620] = "obj_pyro_fireball2";
	global.__objectNames[621] = "obj_pl_flame";
	global.__objectNames[622] = "obj_pl_flaregun";
	global.__objectNames[623] = "obj_pl_flare";
	global.__objectNames[624] = "obj_pl_flaregunspawn";
	global.__objectNames[625] = "obj_pl_flareexhaust";
	global.__objectNames[626] = "obj_pl_gas";
	global.__objectNames[627] = "obj_pl_flamethrower";
	global.__objectNames[628] = "obj_pl_rocket";
	global.__objectNames[629] = "obj_pl_explode";
	global.__objectNames[630] = "obj_pl_axe";
	global.__objectNames[631] = "obj_pl_flamewaves";
	global.__objectNames[632] = "obj_pl_flamewaves2";
	global.__objectNames[633] = "obj_pl_hpandgun";
	global.__objectNames[634] = "obj_pl_pyro_battle";
	global.__objectNames[635] = "obj_pl_fight";
	global.__objectNames[636] = "obj_pl_pyro_barrier";
	global.__objectNames[637] = "obj_pl_pyro_barrier2";
	global.__objectNames[638] = "obj_pl_damage_numbers";
	global.__objectNames[639] = "obj_pl_whitenoise";
	global.__objectNames[640] = "obj_pl_text_box";
	global.__objectNames[641] = "balloonattackparent";
	global.__objectNames[642] = "obj_pl_act";
	global.__objectNames[643] = "obj_pl_helpbox";
	global.__objectNames[644] = "obj_pl_balloonicorn1";
	global.__objectNames[645] = "obj_pl_balloonicorn5";
	global.__objectNames[646] = "obj_pl_balloonicorn6";
	global.__objectNames[647] = "obj_pl_balloonicorn3";
	global.__objectNames[648] = "obj_pl_balloonicorn4";
	global.__objectNames[649] = "obj_pl_balloonicorn2";
	global.__objectNames[650] = "obj_pl_tranquilizer";
	global.__objectNames[651] = "obj_pl_crosshair";
	global.__objectNames[652] = "obj_pl_tranqdart";
	global.__objectNames[653] = "obj_pl_gear";
	global.__objectNames[654] = "obj_pl_nail";
	global.__objectNames[655] = "obj_pl_dynamite1";
	global.__objectNames[656] = "obj_pl_dynamite2";
	global.__objectNames[657] = "obj_pl_dynamite_saved";
	global.__objectNames[658] = "obj_pl_boom";
	global.__objectNames[659] = "obj_pl_rpg";
	global.__objectNames[660] = "obj_pl_arrow";
	global.__objectNames[661] = "obj_pl_bow";
	global.__objectNames[662] = "obj_pl_rpgrocket";
	global.__objectNames[663] = "obj_pl_b_finale";
	global.__objectNames[664] = "obj_pl_f_balloonicorn";
	global.__objectNames[665] = "obj_pl_f_balloonihelp";
	global.__objectNames[666] = "obj_pl_pyrodeath";
	global.__objectNames[667] = "obj_pl_whitescreen";
	global.__objectNames[668] = "obj_pl_finalpyro";
	global.__objectNames[669] = "obj_pl_ballooney2";
	global.__objectNames[670] = "obj_pl_whitescreen2";
	global.__objectNames[671] = "obj_th_fog";
	global.__objectNames[672] = "obj_th_door";
	global.__objectNames[673] = "obj_th_call";
	global.__objectNames[674] = "obj_th_call2";
	global.__objectNames[675] = "obj_th_note";
	global.__objectNames[676] = "obj_th_liftblock";
	global.__objectNames[677] = "obj_th_liftbuttons";
	global.__objectNames[678] = "obj_th_terminal";
	global.__objectNames[679] = "obj_th_door1";
	global.__objectNames[680] = "obj_th_door2";
	global.__objectNames[681] = "obj_th_liftbuttons2";
	global.__objectNames[682] = "obj_th_key1";
	global.__objectNames[683] = "obj_th_key1call";
	global.__objectNames[684] = "obj_th_janegrip";
	global.__objectNames[685] = "obj_th_key2";
	global.__objectNames[686] = "obj_th_eli_portrait";
	global.__objectNames[687] = "obj_th_key3";
	global.__objectNames[688] = "obj_th_generator";
	global.__objectNames[689] = "obj_tpe_misha1";
	global.__objectNames[690] = "obj_tpe_syringe";
	global.__objectNames[691] = "obj_tpe_sani1";
	global.__objectNames[692] = "obj_tpe_misha2";
	global.__objectNames[693] = "obj_tpe_demo";
	global.__objectNames[694] = "obj_tpe_eli1";
	global.__objectNames[695] = "obj_tpe_scout1";
	global.__objectNames[696] = "obj_tpe_dell";
	global.__objectNames[697] = "obj_tpe_jane";
	global.__objectNames[698] = "obj_tpe_sniper";
	global.__objectNames[699] = "obj_tpe_spy";
	global.__objectNames[700] = "obj_tpe_ballooney1";
	global.__objectNames[701] = "obj_tpe_saves";
	global.__objectNames[702] = "obj_tpe_soul1";
	global.__objectNames[703] = "obj_tpe_letter";
	global.__objectNames[704] = "obj_endbox";
	global.__objectNames[705] = "obj_tpe_gunsnmercs";
	global.__objectNames[706] = "obj_tpe_flashback";
	global.__objectNames[707] = "obj_tpe_background";
	global.__objectNames[708] = "obj_tpe_ballooney2";
	global.__objectNames[709] = "obj_tpe_mercs";
	global.__objectNames[710] = "obj_tpe_evade_ground";
	global.__objectNames[711] = "obj_tpe_soulmove";
	global.__objectNames[712] = "obj_tpe_evade_soul";
	global.__objectNames[713] = "obj_tpe_death";
	global.__objectNames[714] = "obj_tpe_danger_zones";
	global.__objectNames[715] = "obj_tpe_misha_bullet";
	global.__objectNames[716] = "obj_tpe_bullet_follow2";
	global.__objectNames[717] = "obj_tpe_jar_drop";
	global.__objectNames[718] = "obj_tpe_jar";
	global.__objectNames[719] = "obj_tpe_crosshair";
	global.__objectNames[720] = "obj_tpe_battle_bullet";
	global.__objectNames[721] = "obj_tpe_blackscreen";
	global.__objectNames[722] = "obj_tpe_bonesaw";
	global.__objectNames[723] = "obj_tpe_syringe_gun";
	global.__objectNames[724] = "obj_tpe_fight";
	global.__objectNames[725] = "obj_tpe_finalgoodbye";
	global.__objectNames[726] = "obj_tpe_finalballooney";
	global.__objectNames[727] = "obj_tpe_outro1";
	global.__objectNames[728] = "obj_tpe_outro2";
	global.__objectNames[729] = "obj_tpe_dell2";
	global.__objectNames[730] = "obj_tpe_jane2";
	global.__objectNames[731] = "obj_tpe_demo2";
	global.__objectNames[732] = "obj_tpe_eli2";
	global.__objectNames[733] = "obj_tpe_misha3";
	global.__objectNames[734] = "obj_tpe_sani2";
	global.__objectNames[735] = "obj_tpe_cast1";
	global.__objectNames[736] = "obj_tpe_cast2";
	global.__objectNames[737] = "obj_tpe_cast3";
	global.__objectNames[738] = "obj_tpe_cast4";
	global.__objectNames[739] = "obj_tpe_cast5";
	global.__objectNames[740] = "obj_tpe_cast6";
	global.__objectNames[741] = "obj_tpe_cast7";
	global.__objectNames[742] = "obj_tpe_castmember";
	global.__objectNames[743] = "obj_tpe_photo";
	global.__objectNames[744] = "obj_tpe_credits";
	global.__objectNames[745] = "obj_tpe_special_mentions";
	global.__objectNames[746] = "obj_tpe_richard";
	global.__objectNames[747] = "obj_crowbar_item";
	global.__objectNames[748] = "obj_syringe_item2";
	global.__objectNames[749] = "obj_syringe_item1";
	global.__objectNames[750] = "obj_jarate_item";
	global.__objectNames[751] = "obj_sapper_item";
	global.__objectNames[752] = "obj_intro_load_progress";
	global.__objectNames[753] = "obj_name_input";
	global.__objectNames[754] = "obj_controls";
	global.__objectNames[755] = "obj_intro";
	global.__objectNames[756] = "obj_main_menu";
	global.__objectNames[757] = "obj_intro_whitescreen";
	global.__objectNames[758] = "obj_i_ballooney";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
