draw_sprite_ext(spr_misha_battle, 2, x, y, 1, 1, 0, image_blend, image_alpha)
draw_sprite_ext(spr_misha_battle, 0, x, (y - (shaking / 4)), 1, 1, 0, image_blend, image_alpha)
draw_sprite_ext(spr_misha_battle, 1, x, (y - (shaking / 8)), 1, 1, 0, image_blend, image_alpha)
draw_sprite_ext(spr_misha_battle_head, heads, x, ((y - 10) - (shaking / 8)), 1, 1, 0, image_blend, image_alpha)
draw_sprite_ext(spr_misha_battle, 3, x, (y - (shaking / 2)), 1, 1, 0, image_blend, image_alpha)
draw_sprite_ext(spr_mbros_flash, 0, (-48 + (((extend4 + extend3) + extend2) + extend1)), (-48 + (((extend4 + extend3) + extend2) + extend1)), 1, 1, 0, make_color_rgb(74, 0, 12), image_alpha)
draw_sprite_ext(spr_mbros_flash, 0, (-50 + ((extend4 + extend3) + extend2)), (-50 + ((extend4 + extend3) + extend2)), 1, 1, 0, make_color_rgb(136, 0, 21), image_alpha)
draw_sprite_ext(spr_mbros_flash, 0, (-54 + (extend4 + extend3)), (-54 + (extend4 + extend3)), 1, 1, 0, make_color_rgb(171, 14, 21), image_alpha)
draw_sprite_ext(spr_mbros_flash, 0, (-60 + extend4), (-60 + extend4), 1, 1, 0, make_color_rgb(237, 28, 36), image_alpha)
draw_sprite_ext(spr_mbros_flash, 0, ((((320 - extend4) - extend3) - extend2) - extend1), ((((0 - extend4) - extend3) - extend2) - extend1), -1, 1, 0, make_color_rgb(0, 0, 74), image_alpha)
draw_sprite_ext(spr_mbros_flash, 0, (((316 - extend4) - extend3) - extend2), (((-4 - extend4) - extend3) - extend2), -1, 1, 0, make_color_rgb(40, 40, 190), image_alpha)
draw_sprite_ext(spr_mbros_flash, 0, ((312 - extend4) - extend3), ((-8 - extend4) - extend3), -1, 1, 0, make_color_rgb(70, 70, 210), image_alpha)
draw_sprite_ext(spr_mbros_flash, 0, (308 - extend4), (-12 - extend4), -1, 1, 0, make_color_rgb(110, 110, 210), image_alpha)
draw_text(30, 140, string_hash_to_newline(("x " + string(bluex))))
draw_text(30, 150, string_hash_to_newline(("y " + string(bluey))))
draw_text(30, 170, string_hash_to_newline(("xscale " + string(bluexscale))))
draw_text(30, 180, string_hash_to_newline(("yscale " + string(blueyscale))))
draw_text(25, 140, string_hash_to_newline(("Time: " + string(global.evadetime))))
draw_text(25, 160, string_hash_to_newline(("A3: " + string(alarm[3]))))
draw_text(25, 180, string_hash_to_newline(("Punching: " + string(punching))))
draw_text(215, 140, string_hash_to_newline(("Chance: " + string(attackchance))))
draw_text(215, 160, string_hash_to_newline(("Attack: " + string(attacking))))

