scr_enemy_variables()
enemyname = "??????"
enemyquip = "Life is unfair to us all."
enemyinfo = "It has very dry humor."
enemyhealth = 666
maxhealth = 666
sparemeter = 15
enemyattack = 4
enemydefense = 2
giantdamagebar = 0
xpreceive = round(random_range(3, 5))
cashreceive = round(random_range(3, 4))
act1 = "Pet"
pether = 0
act2 = "Listen"
listened = 0
act3 = "Moisturize"
moisturized = 0
act4 = "???"
healthysprite = 420
hurtsprite = 421
downsprite = 421
image_speed = 0
animprog = 0
counter = 0
eyeprogress = 0
tailangle = 9
leftorright = 0
extrahead = 0
leg1x = 0
leg1y = 0
leg1updown = 0
leg2x = 0
leg2y = 0
leg2updown = 0
headshakex = 0
headshakey = 0
jaw1x = irandom_range(-20, 20)
jaw1y = irandom_range(-20, 20)

