if (soulhit == 1)
    draw_sprite_ext(sprite_index, image_index, x, y, 0.5, 0.5, 0, c_black, 1)
if (global.soultype == 0)
    draw_sprite_ext(sprite_index, image_index, x, y, 0.5, 0.5, 0, image_blend, image_alpha)
if (global.soultype == 1)
    draw_sprite_ext(spr_soul_white, image_index, x, y, 0.5, 0.5, 0, c_orange, image_alpha)
if (global.soultype == 2)
    draw_sprite_ext(spr_soul_white, image_index, x, y, 0.5, 0.5, 0, c_green, image_alpha)
if (global.soultype == 3)
{
    draw_line_width_colour(128, 140, 191, 140, 0.5, c_purple, c_purple)
    draw_line_width_colour(128, 160, 191, 160, 0.5, c_purple, c_purple)
    draw_line_width_colour(128, 180, 191, 180, 0.5, c_purple, c_purple)
    draw_sprite_ext(spr_soul_white, image_index, x, y, 0.5, 0.5, 0, c_purple, image_alpha)
}
if (global.soultype == 4)
    draw_sprite_ext(spr_soul_white, image_index, x, y, 0.5, 0.5, 0, c_yellow, image_alpha)
if (global.soultype == 5)
    draw_sprite_ext(spr_soul_white, image_index, x, y, 0.5, 0.5, 0, c_blue, image_alpha)
if (nohud == 0)
{
    draw_set_font(font_battle_big)
    draw_text_transformed(16, 200, string_hash_to_newline(global.playername), 0.5, 0.5, 0)
    draw_text_transformed(66, 200, string_hash_to_newline("LV"), 0.5, 0.5, 0)
    draw_text_transformed(86, 200, string_hash_to_newline(global.playerlevel), 0.5, 0.5, 0)
    draw_text_transformed(118, 200, string_hash_to_newline("HP"), 0.5, 0.5, 0)
    if (global.playerhealth > 9)
        draw_text_transformed(158, 200, string_hash_to_newline(((string(global.playerhealth) + " / ") + string(global.fullhealth))), 0.5, 0.5, 0)
    if (global.playerhealth <= 9)
        draw_text_transformed(158, 200, string_hash_to_newline(((("0" + string(global.playerhealth)) + " / ") + string(global.fullhealth))), 0.5, 0.5, 0)
    if (global.playerhealth <= 0)
        draw_text_transformed(158, 200, string_hash_to_newline(("00 / " + string(global.fullhealth))), 0.5, 0.5, 0)
    draw_sprite(spr_redbar, 0, 138, 200)
    draw_sprite_stretched(spr_healthbar, 0, 138, 200, 12, (12 - round(((12 / global.fullhealth) * global.playerhealth))))
    draw_sprite(spr_health_plus, 0, 138, 200)
}

