if (global.soultype == 0)
    draw_sprite_ext(spr_soul, image_index, global.soulxposition, global.soulyposition, 0.5, 0.5, 0, image_blend, image_alpha)
if (global.soultype == 2)
    draw_sprite_ext(spr_soul_white, image_index, global.soulxposition, global.soulyposition, 0.5, 0.5, 0, c_green, image_alpha)
draw_sprite(spr_tavish_battle, 5, x, y)
draw_sprite(spr_tavish_battle, 4, x, y)
draw_sprite(spr_tavish_battle, 3, x, y)
if (progress == 5)
    draw_sprite_ext(spr_sword_slash, image_index, (x - 27), (y + 16), 0.5, 0.5, 0, image_blend, image_alpha)
if (progress < 5 || progress > 6)
    draw_sprite_ext(spr_tavish_arm, 0, (x - 17), (y - 19), 1, 1, (-armturn), image_blend, image_alpha)
draw_sprite(spr_tavish_battle, 1, x, y)
if (progress > 3 && progress < 7)
    draw_sprite_ext(spr_tavish_arm, 0, (x - 17), (y - 19), 1, 1, (-armturn), image_blend, image_alpha)
draw_sprite_ext(spr_tavish_arm, 1, (x - 17), (y - 19), 1, 1, 0, image_blend, image_alpha)
draw_sprite(spr_tavish_heads, head, x, y)

