scr_enemy_variables()
global.dellhired = 0
global.dellkilled = 0
global.reloaddellhired = 0
global.reloaddellkilled = 0
enemyname = "dell."
enemyquip = "the easiest mercenary."
enemyinfo = "not much to add."
enemyhealth = 1
maxhealth = 1
sparemeter = 35
enemyattack = 5
enemydefense = 2
giantdamagebar = 1
cashreceive = 0
xpreceive = round(random_range(5, 9))
act1 = "Joke"
act2 = "Insult"
act3 = "Flee"
act4 = "???"
healthysprite = 583
hurtsprite = 583
downsprite = 583
heads = 0
torso = 0
extrax = 0
extray = 0
animprog = 0
moveaway = 0
moveawayx = 0
global.dellprogress = 1
image_speed = 0
geno = 0
isdying = 0
diestoo = 0
meterdown = 0
sparingyou = 0
phasetwo = 0
counter = 0
phasetwoinitiated = 0
exhausted = 0

