if ((!(place_meeting(x, y, obj_enemy_spared))) && enemyhealth > 0 && enemyhurt == 0 && enemydead == 0)
{
    draw_sprite_ext(spr_wizard_battle, 1, x, ((y - 2) + (shaking * 1.25)), 1, 1, 0, image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_battle, 0, x, ((y - 2) + (shaking * 1.5)), 1, 1, 0, image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_battle, 2, (x - (shaking / 4)), y, 1, 1, (shaking * 3), image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_battle, 3, (x + (shaking / 4)), y, 1, 1, ((-shaking) * 3), image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_battle, 4, x, (y + (shaking / 4)), 1, 1, 0, image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_battle, 5, ((x + 12) - (shaking / 4)), ((y + 12) - (shaking / 4)), 1, 1, (-32 - (shaking * 3)), image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_battle, 6, ((x - 12) + (shaking / 4)), ((y + 12) - (shaking / 4)), 1, 1, (32 + (shaking * 3)), image_blend, image_alpha)
    if (attacking == 0)
        draw_sprite_ext(spr_wizard_battle, 7, (x - (shaking / 4)), (y - (shaking / 4)), 1, 1, ((-shaking) * 3), image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_battle, 8, (x + (shaking / 4)), (y - (shaking / 4)), 1, 1, (shaking * 3), image_blend, image_alpha)
    if (sparemeter > 0)
        draw_sprite_ext(spr_wizard_battle, 9, x, (y + (shaking / 3)), 1, 1, 0, image_blend, image_alpha)
    if (sparemeter > 5)
        draw_sprite_ext(spr_wizard_battle, 10, x, (y + (shaking / 3)), 1, 1, 0, image_blend, image_alpha)
    if (attacking == 0)
        draw_sprite_ext(spr_wizard_electro, image_index, (x - 30), ((y - 14) - (shaking * 3)), (1 + (electroshake / 8)), (1 + (electroshake / 6)), 0, image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_electro, image_index, (x + 30), ((y - 14) - (shaking * 3)), (-1 - (electroshake / 8)), (-1 - (electroshake / 6)), 0, image_blend, image_alpha)
}
if ((place_meeting(x, y, obj_enemy_spared) || enemyhealth <= 0) && enemydead == 0)
{
    draw_sprite_ext(spr_wizard_battle, 1, x, y, 1, 1, 0, image_blend, 0.5)
    draw_sprite_ext(spr_wizard_battle, 0, x, y, 1, 1, 0, image_blend, 0.5)
    draw_sprite_ext(spr_wizard_battle, 2, x, y, 1, 1, 0, image_blend, 0.5)
    draw_sprite_ext(spr_wizard_battle, 3, x, y, 1, 1, 0, image_blend, 0.5)
    draw_sprite_ext(spr_wizard_battle, 4, x, y, 1, 1, 0, image_blend, 0.5)
    draw_sprite_ext(spr_wizard_battle, 5, (x + 12), (y + 12), 1, 1, -32, image_blend, 0.5)
    draw_sprite_ext(spr_wizard_battle, 6, (x - 12), (y + 12), 1, 1, 32, image_blend, 0.5)
    draw_sprite_ext(spr_wizard_battle, 7, x, y, 1, 1, 0, image_blend, 0.5)
    draw_sprite_ext(spr_wizard_battle, 8, x, y, 1, 1, 0, image_blend, 0.5)
    if (sparemeter > 0)
        draw_sprite_ext(spr_wizard_battle, 9, x, y, 1, 1, 0, image_blend, 0.5)
    if (sparemeter > 5)
        draw_sprite_ext(spr_wizard_battle, 10, x, y, 1, 1, 0, image_blend, 0.5)
}
if (enemyhurt == 1 && enemydead == 0)
{
    draw_sprite_ext(spr_wizard_battle, 1, x, y, 1, 1, 0, image_blend, 0.5)
    draw_sprite_ext(spr_wizard_battle, 0, x, y, 1, 1, 0, image_blend, 0.5)
    draw_sprite_ext(spr_wizard_battle, 2, x, y, 1, 1, 0, image_blend, 0.5)
    draw_sprite_ext(spr_wizard_battle, 3, x, y, 1, 1, 0, image_blend, 0.5)
    draw_sprite_ext(spr_wizard_battle, 4, x, y, 1, 1, 0, image_blend, 0.5)
    draw_sprite_ext(spr_wizard_battle, 5, (x + 12), (y + 12), 1, 1, -32, image_blend, 0.5)
    draw_sprite_ext(spr_wizard_battle, 6, (x - 12), (y + 12), 1, 1, 32, image_blend, 0.5)
    draw_sprite_ext(spr_wizard_battle, 7, x, y, 1, 1, 0, image_blend, 0.5)
    draw_sprite_ext(spr_wizard_battle, 8, x, y, 1, 1, 0, image_blend, 0.5)
    if (sparemeter > 0)
        draw_sprite_ext(spr_wizard_battle, 9, x, y, 1, 1, 0, image_blend, 0.5)
    if (sparemeter > 5)
        draw_sprite_ext(spr_wizard_battle, 10, x, y, 1, 1, 0, image_blend, 0.5)
}
if (enemydead == 1)
{
    draw_sprite_ext(spr_wizard_battle, 1, x, y, 1, 1, 0, image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_battle, 0, x, y, 1, 1, 0, image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_battle, 2, x, y, 1, 1, 0, image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_battle, 3, x, y, 1, 1, 0, image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_battle, 4, x, y, 1, 1, 0, image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_battle, 5, (x + 12), (y + 12), 1, 1, -32, image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_battle, 6, (x - 12), (y + 12), 1, 1, 32, image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_battle, 7, x, y, 1, 1, 0, image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_battle, 8, x, y, 1, 1, 0, image_blend, image_alpha)
    if (sparemeter > 0)
        draw_sprite_ext(spr_wizard_battle, 9, x, y, 1, 1, 0, image_blend, image_alpha)
    if (sparemeter > 5)
        draw_sprite_ext(spr_wizard_battle, 10, x, y, 1, 1, 0, image_blend, image_alpha)
}
scr_enemy_draw_healthbar()

