draw_set_font(font_standard)
draw_set_color(c_red)
if (progress == 0)
    draw_text_ext(10, 10, string_hash_to_newline((("> " + string_copy(STR[0], 1, POS)) + string(underscore))), 18, 320)
if (progress > 0)
    draw_text_ext(10, 10, string_hash_to_newline("> Error: RM_INTRO crashed."), 18, 320)
draw_set_color(c_lime)
if (progress == 2)
    draw_text_ext(10, 28, string_hash_to_newline((("> " + string_copy(STR[1], 1, POS)) + string(underscore))), 18, 320)
if (progress > 2)
    draw_text_ext(10, 28, string_hash_to_newline("> Redirecting to RM_MAIN_MENU."), 18, 320)
draw_set_color(c_red)
if (progress == 4)
    draw_text_ext(10, 46, string_hash_to_newline((("> " + string_copy(STR[2], 1, POS)) + string(underscore))), 18, 320)
if (progress > 4)
    draw_text_ext(10, 46, string_hash_to_newline("> Error: RM_MAIN_MENU not found."), 18, 320)
draw_set_color(c_lime)
if (progress == 6)
    draw_text_ext(10, 64, string_hash_to_newline((("> " + string_copy(STR[3], 1, POS)) + string(underscore))), 18, 320)
if (progress > 6)
    draw_text_ext(10, 64, string_hash_to_newline("> Loading save OVERTIME.SAV"), 18, 320)
draw_set_color(c_red)
if (progress == 8)
    draw_text_ext(10, 82, string_hash_to_newline((("> " + string_copy(STR[4], 1, POS)) + string(underscore))), 18, 320)
if (progress > 8)
    draw_text_ext(10, 82, string_hash_to_newline("> Error: OVERTIME.SAV not found."), 18, 320)
draw_set_color(c_lime)
if (progress == 10)
    draw_text_ext(10, 100, string_hash_to_newline((("> " + string_copy(STR[5], 1, POS)) + string(underscore))), 18, 320)
if (progress > 10)
    draw_text_ext(10, 100, string_hash_to_newline("> Restoring last available backup."), 18, 320)
if (progress == 12)
    draw_text_ext(10, 118, string_hash_to_newline((("> " + string_copy(STR[6], 1, POS)) + string(underscore))), 18, 320)
if (progress > 12)
    draw_text_ext(10, 118, string_hash_to_newline("> 3"), 18, 320)
if (progress == 14)
    draw_text_ext(10, 136, string_hash_to_newline((("> " + string_copy(STR[7], 1, POS)) + string(underscore))), 18, 320)
if (progress > 14)
    draw_text_ext(10, 136, string_hash_to_newline("> 2"), 18, 320)
if (progress == 16)
    draw_text_ext(10, 154, string_hash_to_newline((("> " + string_copy(STR[8], 1, POS)) + string(underscore))), 18, 320)
if (progress > 16)
    draw_text_ext(10, 154, string_hash_to_newline("> 1"), 18, 320)
draw_sprite_ext(spr_blacklines, 0, 0, 0, 1, 1, 0, c_black, 0.3)

