if (castmember == 0)
{
    draw_set_font(font_huge)
    draw_set_color(c_white)
    draw_text(79, (y + 30), string_hash_to_newline("Crying Cat"))
    draw_sprite(spr_ccat, image_index, 160, (y + 120))
    draw_set_color(c_yellow)
    draw_set_font(font_standard)
    draw_text(108, (y + 188), string_hash_to_newline("Still waiting#for an update"))
}
if (castmember == 1)
{
    draw_set_font(font_huge)
    draw_set_color(c_white)
    draw_text(79, (y + 30), string_hash_to_newline("Irate Sven"))
    draw_sprite(spr_battle_sven, image_index, 160, (y + 120))
    draw_set_color(c_yellow)
    draw_set_font(font_standard)
    draw_text(108, (y + 188), string_hash_to_newline("Attracts all#the ladies"))
}
if (castmember == 2)
{
    draw_set_font(font_huge)
    draw_set_color(c_white)
    draw_text(47, (y + 30), string_hash_to_newline("Zepheniah Mann"))
    draw_sprite(spr_zepheniah_battle, image_index, 160, (y + 120))
    draw_sprite(spr_zepheniah_bottom, 0, 160, (y + 120))
    draw_set_color(c_yellow)
    draw_set_font(font_standard)
    draw_text(108, (y + 188), string_hash_to_newline("Disappointed#in his sons"))
}
if (castmember == 3)
{
    draw_set_font(font_huge)
    draw_set_color(c_white)
    draw_text(47, (y + 30), string_hash_to_newline("Mobster Magpie"))
    draw_sprite(spr_magpie_battle, image_index, 160, (y + 120))
    draw_set_color(c_yellow)
    draw_set_font(font_standard)
    draw_text(108, (y + 188), string_hash_to_newline("Back in the#Czech Republic"))
}
if (castmember == 4)
{
    draw_set_font(font_huge)
    draw_set_color(c_white)
    draw_text(63, (y + 30), string_hash_to_newline("Greater Birb"))
    draw_sprite(spr_gbirb_battle, image_index, 160, (y + 120))
    draw_set_color(c_yellow)
    draw_set_font(font_standard)
    draw_text(138, (y + 188), string_hash_to_newline("Happy as#always"))
}
if (castmember == 5)
{
    draw_set_font(font_huge)
    draw_set_color(c_white)
    draw_text(71, (y + 30), string_hash_to_newline("Cackledemon"))
    draw_sprite(spr_cackle_battle, image_index, 160, ((y + 120) + float))
    draw_set_color(c_yellow)
    draw_set_font(font_standard)
    draw_text(108, (y + 188), string_hash_to_newline("Life isn't#doomed anymore"))
}
if (castmember == 6)
{
    draw_set_font(font_huge)
    draw_set_color(c_white)
    draw_text(87, (y + 30), string_hash_to_newline("Miniculus"))
    draw_sprite(spr_miniculus_battle, image_index, 160, ((y + 120) + float))
    draw_set_color(c_yellow)
    draw_set_font(font_standard)
    draw_text(130, (y + 188), string_hash_to_newline("Returns#annually"))
}
if (castmember == 7)
{
    draw_set_font(font_huge)
    draw_set_color(c_white)
    draw_text(71, (y + 30), string_hash_to_newline("Ex-Slacker"))
    draw_sprite(spr_slacker_battle, image_index, 160, (y + 120))
    draw_set_color(c_yellow)
    draw_set_font(font_standard)
    draw_text(108, (y + 188), string_hash_to_newline("Now works in#television"))
}
if (castmember == 8)
{
    draw_set_font(font_huge)
    draw_set_color(c_white)
    draw_text(55, (y + 30), string_hash_to_newline("Confused Stan"))
    draw_sprite(spr_stan_battle, image_index, 160, (y + 120))
    draw_set_color(c_yellow)
    draw_set_font(font_standard)
    draw_text(108, (y + 188), string_hash_to_newline("Pushes buttons#for a living"))
}
if (castmember == 9)
{
    draw_set_font(font_huge)
    draw_set_color(c_white)
    draw_text(111, (y + 30), string_hash_to_newline("ST3RM4"))
    draw_sprite(spr_merc_battle, 4, 160, ((y + 120) - (shaking / 4)))
    draw_sprite(spr_merc_battle, 5, 160, (y + 120))
    draw_sprite(spr_merc_battle, 6, 160, ((y + 120) - (shaking / 2)))
    draw_sprite(spr_merc_battle, 7, 160, ((y + 120) - (shaking / 2)))
    draw_sprite(spr_merc_battle, 1, 160, ((y + 120) - (shaking / 4)))
    draw_sprite_ext(spr_merc_battle, 8, 160, (((y + 120) - 10) - (shaking / 2)), 1, 1, 10, image_blend, image_alpha)
    draw_sprite(spr_merc_battle, 0, 160, ((y + 120) - (shaking / 6)))
    draw_set_color(c_yellow)
    draw_set_font(font_standard)
    draw_text(108, (y + 188), string_hash_to_newline("Still loved#by many"))
}
if (castmember == 10)
{
    draw_set_font(font_huge)
    draw_set_color(c_white)
    draw_text(135, (y + 30), string_hash_to_newline("J4R"))
    draw_sprite(spr_merc_battle, 11, 160, ((y + 120) - (shaking / 4)))
    draw_sprite(spr_merc_battle, 5, 160, (y + 120))
    draw_sprite(spr_merc_battle, 6, 160, ((y + 120) - (shaking / 2)))
    draw_sprite(spr_merc_battle, 7, 160, ((y + 120) - (shaking / 2)))
    draw_sprite(spr_merc_battle, 1, 160, ((y + 120) - (shaking / 4)))
    draw_sprite_ext(spr_merc_battle, 8, 160, (((y + 120) - 10) - (shaking / 2)), 1, 1, 10, image_blend, image_alpha)
    draw_sprite(spr_merc_battle, 9, 160, ((y + 120) - (shaking / 6)))
    draw_set_color(c_yellow)
    draw_set_font(font_standard)
    draw_text(128, (y + 188), string_hash_to_newline("Stopped#entirely"))
}
if (castmember == 11)
{
    draw_set_font(font_huge)
    draw_set_color(c_white)
    draw_text(135, (y + 30), string_hash_to_newline("4O4"))
    draw_sprite(spr_merc_battle, 12, 160, ((y + 120) - (shaking / 4)))
    draw_sprite(spr_merc_battle, 5, 160, (y + 120))
    draw_sprite(spr_merc_battle, 6, 160, ((y + 120) - (shaking / 2)))
    draw_sprite(spr_merc_battle, 7, 160, ((y + 120) - (shaking / 2)))
    draw_sprite(spr_merc_battle, 1, 160, ((y + 120) - (shaking / 4)))
    draw_sprite_ext(spr_merc_battle, 8, 160, (((y + 120) - 10) - (shaking / 2)), 1, 1, 10, image_blend, image_alpha)
    draw_sprite(spr_merc_battle, 10, 160, ((y + 120) - (shaking / 6)))
    draw_set_color(c_yellow)
    draw_set_font(font_standard)
    draw_text(108, (y + 188), string_hash_to_newline("Reminisces#about the past"))
}
if (castmember == 12)
{
    draw_set_font(font_huge)
    draw_set_color(c_white)
    draw_text(63, (y + 30), string_hash_to_newline("Weird Wizard"))
    draw_sprite_ext(spr_wizard_battle, 1, 160, (((y + 120) - 2) + (shaking * 1.25)), 1, 1, 0, image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_battle, 0, 160, (((y + 120) - 2) + (shaking * 1.5)), 1, 1, 0, image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_battle, 2, (160 - (shaking / 4)), (y + 120), 1, 1, (shaking * 3), image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_battle, 3, (160 + (shaking / 4)), (y + 120), 1, 1, (-((shaking * 3))), image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_battle, 4, 160, ((y + 120) + (shaking / 4)), 1, 1, 0, image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_battle, 5, (172 - (shaking / 4)), (((y + 120) + 12) - (shaking / 4)), 1, 1, (-32 - (shaking * 3)), image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_battle, 6, (148 + (shaking / 4)), (((y + 120) + 12) - (shaking / 4)), 1, 1, (32 + (shaking * 3)), image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_battle, 7, (160 - (shaking / 4)), ((y + 120) - (shaking / 4)), 1, 1, (-((shaking * 3))), image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_battle, 8, (160 + (shaking / 4)), ((y + 120) - (shaking / 4)), 1, 1, (shaking * 3), image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_battle, 9, 160, ((y + 120) + (shaking / 3)), 1, 1, 0, image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_battle, 10, 160, ((y + 120) + (shaking / 3)), 1, 1, 0, image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_electro, image_index, 130, (((y + 120) - 14) - (shaking * 3)), (1 + (electroshake / 8)), (1 + (electroshake / 6)), 0, image_blend, image_alpha)
    draw_sprite_ext(spr_wizard_electro, image_index, 190, (((y + 120) - 14) - (shaking * 3)), (-1 - (electroshake / 8)), (-1 - (electroshake / 6)), 0, image_blend, image_alpha)
    draw_set_color(c_yellow)
    draw_set_font(font_standard)
    draw_text(108, (y + 188), string_hash_to_newline("Children's#entertainer"))
}
if (castmember == 13)
{
    draw_set_font(font_huge)
    draw_set_color(c_white)
    draw_text(15, (y + 30), string_hash_to_newline("Physical Physician"))
    draw_sprite_ext(spr_physician_battle, 0, 160, (y + 120), 1, 1, 0, image_blend, image_alpha)
    draw_sprite_ext(spr_physician_battle, 1, (160 + shakex), ((y + 120) - (shaking - shakey)), 1, 1, 0, image_blend, image_alpha)
    draw_set_color(c_yellow)
    draw_set_font(font_standard)
    draw_text(128, (y + 188), string_hash_to_newline("Taking a#hiatus"))
}
if (castmember == 14)
{
    draw_set_font(font_huge)
    draw_set_color(c_white)
    draw_text(39, (y + 30), string_hash_to_newline("The Experiments"))
    draw_sprite_ext(spr_hunter_full, 0, 160, (y + 120), 1, 1, 0, image_blend, 1)
    draw_sprite_ext(spr_lethal_full, 0, 60, (y + 120), 1, 1, 0, image_blend, 1)
    draw_sprite_ext(spr_ithurts_full, 0, 260, (y + 120), 1, 1, 0, image_blend, 1)
    draw_sprite_ext(spr_ithurts_weapon, 0, 234, ((y + 120) + 7), 1, 1, 0, image_blend, 1)
    draw_set_color(c_yellow)
    draw_set_font(font_standard)
    draw_text(108, (y + 188), string_hash_to_newline("Finding rest#at last"))
}
draw_set_font(font_standard)
draw_set_color(c_white)

