if (start == 1 && progress < 4)
{
    draw_sprite(spr_menu, 0, __view_get( e__VW.XView, (0 << 0) ), __view_get( e__VW.YView, (0 << 0) ))
    draw_set_font(font_menu)
    draw_set_color(c_white)
    draw_text((__view_get( e__VW.XView, (0 << 0) ) + 23), (__view_get( e__VW.YView, (0 << 0) ) + 31), string_hash_to_newline(string(global.playername)))
    draw_set_font(font_tiny)
    draw_text((__view_get( e__VW.XView, (0 << 0) ) + 23), (__view_get( e__VW.YView, (0 << 0) ) + 47), string_hash_to_newline(("LV   " + string(global.playerlevel))))
    draw_text((__view_get( e__VW.XView, (0 << 0) ) + 23), (__view_get( e__VW.YView, (0 << 0) ) + 56), string_hash_to_newline(("HP   0/" + string(global.fullhealth))))
    draw_text((__view_get( e__VW.XView, (0 << 0) ) + 23), (__view_get( e__VW.YView, (0 << 0) ) + 65), string_hash_to_newline(("A    " + string(global.australium))))
    draw_set_font(font_menu)
    draw_text((__view_get( e__VW.XView, (0 << 0) ) + 42), (__view_get( e__VW.YView, (0 << 0) ) + 95), string_hash_to_newline("ITEM"))
    draw_text((__view_get( e__VW.XView, (0 << 0) ) + 42), (__view_get( e__VW.YView, (0 << 0) ) + 113), string_hash_to_newline("NOTE"))
    draw_text((__view_get( e__VW.XView, (0 << 0) ) + 42), (__view_get( e__VW.YView, (0 << 0) ) + 131), string_hash_to_newline("CELL"))
    draw_set_color(c_white)
    draw_set_font(font_menu)
    if (progress < 2)
        draw_sprite(spr_soul_small, 0, (__view_get( e__VW.XView, (0 << 0) ) + 32), (__view_get( e__VW.YView, (0 << 0) ) + 103))
    if (progress == 2)
        draw_sprite(spr_soul_small, 0, (__view_get( e__VW.XView, (0 << 0) ) + 32), (__view_get( e__VW.YView, (0 << 0) ) + 121))
    if (progress == 3)
        draw_sprite(spr_soul_small, 0, (__view_get( e__VW.XView, (0 << 0) ) + 32), (__view_get( e__VW.YView, (0 << 0) ) + 139))
}
if (progress > 4)
{
    draw_sprite(spr_textbox, 0, __view_get( e__VW.XView, (0 << 0) ), __view_get( e__VW.YView, (0 << 0) ))
    draw_set_color(c_white)
    draw_set_font(font_jane)
    draw_sprite(spr_jane_face_grip, janeface, (__view_get( e__VW.XView, (0 << 0) ) + 27), (__view_get( e__VW.YView, (0 << 0) ) + 164))
    draw_text_ext((__view_get( e__VW.XView, view_current ) + 88), (__view_get( e__VW.YView, view_current ) + 170), string_hash_to_newline("GAAAAAAAARGH...."), 18, 237)
    draw_set_color(c_white)
    draw_set_font(font_standard)
}

