if ((!(place_meeting(x, y, obj_enemy_spared))) && enemyhealth > 0 && enemyhurt == 0 && enemydead == 0)
    draw_sprite(healthysprite, image_index, x, y)
if ((place_meeting(x, y, obj_enemy_spared) || enemyhealth <= 0) && enemydead == 0)
    draw_sprite(downsprite, image_index, x, y)
if (enemyhurt == 1 && enemydead == 0)
    draw_sprite(hurtsprite, image_index, x, y)
if (enemydead == 1)
    draw_sprite_ext(downsprite, image_index, x, y, 1, 1, 0, image_blend, image_alpha)
scr_enemy_draw_healthbar()

