draw_set_color(c_white)
draw_set_font(font_huge)
draw_text(182, 168, string_hash_to_newline("TAVISH"))
draw_set_color(c_yellow)
draw_set_font(font_standard)
draw_text(182, 200, string_hash_to_newline("Fought Loch#Ness monster"))
draw_sprite_ext(spr_blackscreen, 0, 170, 200, 1, 1, 0, image_blend, tavishblack)
draw_set_color(c_white)
draw_set_font(font_huge)
draw_text(32, 152, string_hash_to_newline("ELI"))
draw_set_color(c_yellow)
draw_set_font(font_standard)
draw_text(26, 193, string_hash_to_newline("Making#progress"))
draw_sprite_ext(spr_blackscreen, 0, -210, 180, 1, 1, 0, image_blend, eliblack)
draw_set_font(font_standard)
draw_set_color(c_white)

