draw_set_color(c_white)
draw_set_font(font_huge)
draw_text(190, 154, string_hash_to_newline("DELL"))
draw_set_color(c_yellow)
draw_set_font(font_standard)
draw_text(185, 190, string_hash_to_newline("Building#more guns"))
draw_sprite_ext(spr_blackscreen, 0, 140, 180, 1, 1, 0, image_blend, dellblack)
draw_set_color(c_white)
draw_set_font(font_huge)
draw_text(60, 154, string_hash_to_newline("JANE"))
draw_set_color(c_yellow)
draw_set_font(font_standard)
draw_text(55, 190, string_hash_to_newline("Screaming#at eagles"))
draw_sprite_ext(spr_blackscreen, 0, -190, 180, 1, 1, 0, image_blend, janeblack)
if (progress >= 4)
{
    draw_set_color(c_white)
    draw_set_font(font_huge)
    draw_text(40, 160, string_hash_to_newline("MUNDY"))
    draw_set_color(c_yellow)
    draw_set_font(font_standard)
    draw_text(31, 199, string_hash_to_newline("Good outlook#on life"))
    draw_sprite_ext(spr_blackscreen, 0, 0, 140, 1, 1, 0, image_blend, sniperblack)
}
draw_set_font(font_standard)
draw_set_color(c_white)

