audio_play_sound(snd_spare, 1, false)
progress = 17
instance_create(x, y, obj_misha_heart)
instance_create((x + random_range(0, -48)), (y + random_range(0, -12)), obj_deathflames)
instance_create((x + random_range(0, -48)), (y + random_range(-12, -24)), obj_deathflames)
instance_create((x + random_range(0, -48)), (y + random_range(-24, -48)), obj_deathflames)
instance_create((x + random_range(0, 48)), (y + random_range(0, -12)), obj_deathflames)
instance_create((x + random_range(0, 48)), (y + random_range(-12, -24)), obj_deathflames)
instance_create((x + random_range(0, 48)), (y + random_range(-24, -48)), obj_deathflames)
instance_create((x + random_range(0, 48)), (y + random_range(0, 12)), obj_deathflames)
instance_create((x + random_range(0, 48)), (y + random_range(12, 24)), obj_deathflames)
instance_create((x + random_range(0, 48)), (y + random_range(24, 48)), obj_deathflames)
instance_create((x + random_range(0, -48)), (y + random_range(0, 12)), obj_deathflames)
instance_create((x + random_range(0, -48)), (y + random_range(12, 24)), obj_deathflames)
instance_create((x + random_range(0, -48)), (y + random_range(24, 48)), obj_deathflames)
